/-
Copyright (c) 2026 Paulo Rauber. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Paulo Rauber, Rémy Degenne
-/
module

public import LeanMachineLearning.SequentialLearning.Comap
public import LeanMachineLearning.SequentialLearning.IonescuTulceaSpace
public import LeanMachineLearning.SequentialLearning.StationaryEnv

/-!
# Bayesian stationary environments

A Bayesian stationary environment is an environment that draws a parameter `e : 𝓔` from a prior
`Q` before the first round and then behaves like the stationary environment
`stationaryEnv (κ.sectR e)`. Concretely, `bayesStationaryEnv Q κ : Environment 𝓔 𝓐 𝓨` announces
an observation `e` at every round and runs against `alg.comapObs (fun _ ↦ ())`, for
an `alg : Algorithm Unit 𝓐 𝓨`, an algorithm that does not use the observation.

## Main definitions

* `bayesStationaryEnv Q κ`: the environment that draws a parameter from `Q` before the first
  round, announces it as the observation of every round, and returns feedback `κ (e, a)` when the
  parameter is `e` and the action is `a`.
* `IsBayesAlgEnvSeq Q κ alg E A Y P`: states that the parameter `E : Ω → 𝓔` has law `Q` and that
  the sequences of actions `A : ℕ → Ω → 𝓐` and feedbacks `Y : ℕ → Ω → 𝓨` are generated by the
  algorithm `alg : Algorithm Unit 𝓐 𝓨` interacting with `bayesStationaryEnv Q κ`, which it sees
  through `Algorithm.comapObs (fun _ ↦ ())`. Equivalently, `A` and `Y` are generated by `alg`
  interacting with the stationary environment `stationaryEnv (κ.sectR (E ω))`.
* `bayesTrajMeasure Q κ alg`: for any choice of probability measure `Q : Measure 𝓔`, Markov kernel
  `κ : Kernel (𝓔 × 𝓐) 𝓨`, and algorithm `alg : Algorithm Unit 𝓐 𝓨`, provides a probability measure
  `P : Measure (ℕ → Round 𝓔 𝓐 𝓨)` on a space that carries `E`, `A`, and `Y` such that
  `IsBayesAlgEnvSeq Q κ alg E A Y P`.
* `bayesTrajMeasurePosterior Q κ alg n`: a `Kernel (Hist Unit 𝓐 𝓨 n) 𝓔` that represents the
  posterior over `E` given the history before time `n` (the `n` first rounds) under
  the prior `Q` and the algorithm `alg`, assuming that the kernel `κ` specifies how `E` gives rise
  to the underlying (stationary) environment.
  See also `LeanMachineLearning/SequentialLearning/AlgorithmDensityBayes.lean`.

## Main results

* `IsAlgEnvSeq.isBayesAlgEnvSeq`: a run of `alg.comapObs (fun _ ↦ ())` against
  `bayesStationaryEnv Q κ` is a Bayesian algorithm-environment sequence for the announced parameter.
* `ae_IsAlgEnvSeq h`: if `h : IsBayesAlgEnvSeq Q κ alg E A Y P`, for `Q`-almost every `e : 𝓔`,
  `IsAlgEnvSeq O' A' Y' alg (stationaryEnv (κ.sectR e)) (condDistrib (trajectory _ A Y) E P e)` for
  some sequence of actions `A' : ℕ → (ℕ → Round Unit 𝓐 𝓨) → 𝓐` and sequence of feedbacks
  `Y' : ℕ → (ℕ → Round Unit 𝓐 𝓨) → 𝓨`. Intuitively, if the observable trajectory is generated by an
  underlying parameter `e : 𝓔`, the measure that carries the `IsBayesAlgEnvSeq` structure reveals a
  measure that carries an `IsAlgEnvSeq` structure under the environment `stationaryEnv (κ.sectR e)`
  and the same algorithm. This allows transferring results from the `IsAlgEnvSeq` structure to the
  `IsBayesAlgEnvSeq` structure.

-/

@[expose] public section

open MeasureTheory ProbabilityTheory Finset
open scoped ENNReal NNReal

namespace Learning

variable {𝓔 𝓐 𝓨 Ω : Type*}
variable [MeasurableSpace 𝓔] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] [MeasurableSpace Ω]

section BayesEnv

/-- The environment that draws a parameter `e : 𝓔` from `Q` before the first round, announces it as
the observation of every round, and returns a feedback drawn from `κ (e, a)` when the action is
`a`. The algorithm is meant to ignore the announced parameter, that is, to run through
`Algorithm.comapObs (fun _ ↦ ())`. -/
noncomputable
def bayesStationaryEnv (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨)
    [IsMarkovKernel κ] : Environment 𝓔 𝓐 𝓨 where
  obs
    | 0 => Kernel.const _ Q
    | _ + 1 => Kernel.deterministic (fun h ↦ (h 0).obs) (by fun_prop)
  feedback _ := κ.comap (fun p ↦ (p.1.2, p.2)) (by fun_prop)
  isMarkovKernel_obs n := by cases n <;> infer_instance

variable {Q : Measure 𝓔} [IsProbabilityMeasure Q] {κ : Kernel (𝓔 × 𝓐) 𝓨} [IsMarkovKernel κ]

@[simp]
lemma obs_bayesStationaryEnv_zero : (bayesStationaryEnv Q κ).obs 0 = Kernel.const _ Q := rfl

@[simp]
lemma obs_bayesStationaryEnv_succ (n : ℕ) :
    (bayesStationaryEnv Q κ).obs (n + 1)
      = Kernel.deterministic (fun h : Hist 𝓔 𝓐 𝓨 (n + 1) ↦ (h 0).obs) (by fun_prop) := rfl

@[simp]
lemma feedback_bayesStationaryEnv (n : ℕ) :
    (bayesStationaryEnv Q κ).feedback n = κ.comap (fun p ↦ (p.1.2, p.2)) (by fun_prop) := rfl

@[simp]
lemma obs0_bayesStationaryEnv : (bayesStationaryEnv Q κ).obs0 = Q := rfl

@[simp]
lemma ν0_bayesStationaryEnv : (bayesStationaryEnv Q κ).ν0 = κ := rfl

end BayesEnv

/-- Insert an announced parameter `e` as the observation of every round of an observable history. -/
def announceHist (e : 𝓔) {n : ℕ} (h : Hist Unit 𝓐 𝓨 n) : Hist 𝓔 𝓐 𝓨 n :=
  fun i ↦ (e, (h i).action, (h i).feedback)

@[fun_prop]
lemma measurable_announceHist (n : ℕ) :
    Measurable (fun p : 𝓔 × Hist Unit 𝓐 𝓨 n ↦ announceHist p.1 p.2) := by
  unfold announceHist
  fun_prop

/-- `IsBayesAlgEnvSeq Q κ alg E A Y P` states that there is a measure `P : Measure Ω` such
that the parameter `E : Ω → 𝓔` has law `Q` and that the sequences of actions `A : ℕ → Ω → 𝓐`
and feedbacks `Y : ℕ → Ω → 𝓨` are generated by the algorithm `alg : Algorithm Unit 𝓐 𝓨`
interacting with an underlying environment that depends on `E` and `κ`
(`stationaryEnv (κ.sectR (E ω))`).

This is `IsAlgEnvSeq` for the announcing environment `bayesStationaryEnv Q κ` and the algorithm
`alg.comapObs (fun _ ↦ ())` that ignores the announced parameter: the observation at every round
is `E ω`. -/
def IsBayesAlgEnvSeq (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨)
    [IsMarkovKernel κ] (alg : Algorithm Unit 𝓐 𝓨)
    (E : Ω → 𝓔) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)
    (P : Measure Ω) [IsProbabilityMeasure P] : Prop :=
  IsAlgEnvSeq (fun _ ↦ E) A Y (alg.comapObs (fun _ : 𝓔 ↦ ())) (bayesStationaryEnv Q κ) P

namespace IsBayesAlgEnvSeq

variable {Q : Measure 𝓔} [IsProbabilityMeasure Q] {κ : Kernel (𝓔 × 𝓐) 𝓨} [IsMarkovKernel κ]
  {alg : Algorithm Unit 𝓐 𝓨} {P : Measure Ω} [IsProbabilityMeasure P]
  {E : Ω → 𝓔} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨}

/-- A Bayesian algorithm-environment sequence is an algorithm-environment sequence for the
announcing environment `bayesStationaryEnv Q κ`. -/
lemma isAlgEnvSeq (h : IsBayesAlgEnvSeq Q κ alg E A Y P) :
    IsAlgEnvSeq (fun _ ↦ E) A Y (alg.comapObs (fun _ : 𝓔 ↦ ())) (bayesStationaryEnv Q κ) P := h

lemma measurable_param (h : IsBayesAlgEnvSeq Q κ alg E A Y P) : Measurable E :=
  h.isAlgEnvSeq.measurable_obs 0

lemma measurable_action (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) : Measurable (A n) :=
  h.isAlgEnvSeq.measurable_action n

lemma measurable_feedback (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) : Measurable (Y n) :=
  h.isAlgEnvSeq.measurable_feedback n

/-- The parameter has law `Q`. -/
lemma hasLaw_env (h : IsBayesAlgEnvSeq Q κ alg E A Y P) : HasLaw E Q P := by
  have h0 := h.isAlgEnvSeq.hasCondDistrib_obs 0
  rw [history_zero] at h0
  exact h0.hasLaw_of_const'

/-- The action at time `n` has the correct conditional distribution given the parameter and the
history: it depends only on the history. -/
lemma hasCondDistrib_action (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    HasCondDistrib (A n) (fun ω ↦ (E ω, (history (noObs Ω) A Y n ω, noObs Ω n ω)))
      ((alg.policy n).prodMkLeft _) P :=
  HasCondDistrib.comp_right
    (f := fun p : Hist 𝓔 𝓐 𝓨 n × 𝓔 ↦ (p.2, (Hist.mapObs (fun _ ↦ ()) p.1, ())))
    (hf := by fun_prop)
    (Z := fun ω ↦ (history (fun _ ↦ E) A Y n ω, E ω))
    (h.isAlgEnvSeq.hasCondDistrib_action n)

/-- The feedback at time `n` has the correct conditional distribution given the history, the
parameter and the action at time `n`: it depends only on the parameter and the action. -/
lemma hasCondDistrib_feedback (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    HasCondDistrib (Y n) (fun ω ↦ ((history (noObs Ω) A Y n ω, noObs Ω n ω), (E ω, A n ω)))
      (κ.prodMkLeft _) P :=
  HasCondDistrib.comp_right
    (f := fun p : (Hist 𝓔 𝓐 𝓨 n × 𝓔) × 𝓐 ↦
      ((Hist.mapObs (fun _ ↦ ()) p.1.1, ()), (p.1.2, p.2)))
    (hf := by fun_prop)
    (Z := fun ω ↦ ((history (fun _ ↦ E) A Y n ω, E ω), A n ω))
    (h.isAlgEnvSeq.hasCondDistrib_feedback n)

lemma hasCondDistrib_action' (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    HasCondDistrib (A n) (fun ω ↦ (history (noObs Ω) A Y n ω, noObs Ω n ω)) (alg.policy n) P :=
  (h.hasCondDistrib_action n).comp_right

lemma hasCondDistrib_feedback' (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    HasCondDistrib (Y n) (fun ω ↦ (E ω, A n ω)) κ P :=
  (h.hasCondDistrib_feedback n).comp_right

lemma hasLaw_action_zero (h : IsBayesAlgEnvSeq Q κ alg E A Y P) :
    HasLaw (A 0) (alg.p0 ()) P := by
  have h0 : HasCondDistrib (A 0)
      (fun _ : Ω ↦ ((default : Hist Unit 𝓐 𝓨 0), ())) (alg.policy 0) P := by
    have h1 := h.hasCondDistrib_action' 0
    rwa [history_zero] at h1
  exact h0.hasLaw_of_const'

/-- The first action is independent of the parameter `E`, and has law `alg.p0 ()`. -/
lemma hasCondDistrib_action_zero (h : IsBayesAlgEnvSeq Q κ alg E A Y P) :
    HasCondDistrib (A 0) E (Kernel.const _ (alg.p0 ())) P :=
  hasCondDistrib_prodMk_right_unique_iff.mp (h.hasCondDistrib_action 0)

/-- The posterior over the parameter given the empty history is the prior. -/
lemma condDistrib_param_history_zero [StandardBorelSpace 𝓔] [Nonempty 𝓔]
    (h : IsBayesAlgEnvSeq Q κ alg E A Y P) :
    condDistrib E (history (noObs Ω) A Y 0) P = Kernel.const _ Q := by
  ext x : 1
  rw [Unique.eq_default x, history_zero]
  have hc : HasCondDistrib E (fun _ : Ω ↦ (default : Hist Unit 𝓐 𝓨 0)) (Kernel.const _ Q) P :=
    h.hasLaw_env.hasCondDistrib_const
  have h_ae := hc.condDistrib_eq
  rw [Measure.map_const, measure_univ, one_smul, Filter.EventuallyEq,
    ae_dirac_iff Subsingleton.measurableSet] at h_ae
  exact h_ae

variable [StandardBorelSpace 𝓐] [Nonempty 𝓐] [StandardBorelSpace 𝓨] [Nonempty 𝓨]

lemma hasCondDistrib_IT_obs (_h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    ∀ᵐ e ∂Q, HasCondDistrib (IT.obs n) (IT.hist n) (Kernel.const _ (Measure.dirac ()))
      (condDistrib (trajectory (noObs Ω) A Y) E P e) :=
  ae_of_all _ fun _ ↦ hasCondDistrib_unit (IT.measurable_hist n).aemeasurable _ _

lemma hasCondDistrib_IT_action (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    ∀ᵐ e ∂Q, HasCondDistrib (IT.action n) (fun τ ↦ (IT.hist n τ, IT.obs n τ)) (alg.policy n)
      (condDistrib (trajectory (noObs Ω) A Y) E P e) := by
  rw [← h.hasLaw_env.map_eq]
  filter_upwards [(h.hasCondDistrib_action n).hasCondDistrib_sectR
    ((IT.measurable_hist n).prodMk (IT.measurable_obs n)) (IT.measurable_action n)
    (measurable_trajectory (O := noObs Ω) (fun _ ↦ measurable_const) h.measurable_action
      h.measurable_feedback).aemeasurable] with _ he
  rwa [Kernel.sectR_prodMkLeft] at he

lemma hasCondDistrib_IT_feedback (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    ∀ᵐ e ∂Q, HasCondDistrib (IT.feedback n)
      (fun τ ↦ ((IT.hist n τ, IT.obs n τ), IT.action n τ))
      ((κ.sectR e).prodMkLeft _) (condDistrib (trajectory (noObs Ω) A Y) E P e) := by
  rw [← h.hasLaw_env.map_eq]
  have hc : HasCondDistrib (Y n)
      (fun ω ↦ (E ω, ((history (noObs Ω) A Y n ω, noObs Ω n ω), A n ω)))
      (κ.comap (fun p : 𝓔 × ((Hist Unit 𝓐 𝓨 n × Unit) × 𝓐) ↦ (p.1, p.2.2)) (by fun_prop)) P :=
    (h.hasCondDistrib_feedback n).measurableEquiv_comp_right (MeasurableEquiv.prodAssoc.symm.trans
      ((MeasurableEquiv.prodCongr .prodComm (.refl _)).trans .prodAssoc))
  exact hc.hasCondDistrib_sectR
    (((IT.measurable_hist n).prodMk (IT.measurable_obs n)).prodMk (IT.measurable_action n))
    (IT.measurable_feedback n)
    (measurable_trajectory (O := noObs Ω) (fun _ ↦ measurable_const) h.measurable_action
      h.measurable_feedback).aemeasurable

lemma hasLaw_IT_hist (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    ∀ᵐ e ∂Q, HasLaw (IT.hist n) (condDistrib (history (noObs Ω) A Y n) E P e)
      (condDistrib (trajectory (noObs Ω) A Y) E P e) := by
  rw [← h.hasLaw_env.map_eq, show history (noObs Ω) A Y n
    = IT.hist (𝓞 := Unit) (𝓐 := 𝓐) (𝓨 := 𝓨) n ∘ trajectory (noObs Ω) A Y from rfl]
  filter_upwards [condDistrib_comp h.measurable_param.aemeasurable
    (measurable_trajectory (O := noObs Ω) (fun _ ↦ measurable_const) h.measurable_action
      h.measurable_feedback).aemeasurable
    (IT.measurable_hist (𝓞 := Unit) (𝓐 := 𝓐) (𝓨 := 𝓨) n)] with _ he
  exact ⟨(IT.measurable_hist n).aemeasurable, by
    rw [← Kernel.map_apply _ (IT.measurable_hist n), he]⟩

lemma ae_IsAlgEnvSeq (h : IsBayesAlgEnvSeq Q κ alg E A Y P) :
    ∀ᵐ e ∂Q, IsAlgEnvSeq IT.obs IT.action IT.feedback alg (stationaryEnv (κ.sectR e))
      (condDistrib (trajectory (noObs Ω) A Y) E P e) := by
  filter_upwards [ae_all_iff.2 (hasCondDistrib_IT_obs h),
    ae_all_iff.2 (hasCondDistrib_IT_action h),
    ae_all_iff.2 (hasCondDistrib_IT_feedback h)] with _ hO hA hR
  exact ⟨IT.measurable_obs, IT.measurable_action, IT.measurable_feedback, hO, hA, hR⟩

end IsBayesAlgEnvSeq

section IsAlgEnvSeq

variable {Q : Measure 𝓔} [IsProbabilityMeasure Q] {κ : Kernel (𝓔 × 𝓐) 𝓨} [IsMarkovKernel κ]
variable {alg : Algorithm Unit 𝓐 𝓨} {O : ℕ → Ω → 𝓔} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨}
variable {P : Measure Ω} [IsProbabilityMeasure P]

/-- Under `bayesStationaryEnv Q κ`, the announced parameter is almost surely the same at every
round. -/
lemma IsAlgEnvSeq.ae_obs_eq_obs_zero [StandardBorelSpace 𝓔]
    (h : IsAlgEnvSeq O A Y (alg.comapObs (fun _ : 𝓔 ↦ ())) (bayesStationaryEnv Q κ) P) (n : ℕ) :
    O 0 =ᵐ[P] O n := by
  cases n with
  | zero => rfl
  | succ n =>
    have h1 := h.hasCondDistrib_obs (n + 1)
    rw [obs_bayesStationaryEnv_succ] at h1
    have h2 := ae_eq_of_hasCondDistrib_deterministic (by fun_prop)
      (h.measurable_history (n + 1)).aemeasurable (h.measurable_obs (n + 1)).aemeasurable h1
    filter_upwards [h2] with ω hω
    rw [hω]
    simp [history_apply]

/-- A run of `alg.comapObs (fun _ ↦ ())` against the announcing environment
`bayesStationaryEnv Q κ` is a Bayesian algorithm-environment sequence for the announced
parameter. -/
lemma IsAlgEnvSeq.isBayesAlgEnvSeq [StandardBorelSpace 𝓔]
    (h : IsAlgEnvSeq O A Y (alg.comapObs (fun _ : 𝓔 ↦ ())) (bayesStationaryEnv Q κ) P) :
    IsBayesAlgEnvSeq Q κ alg (O 0) A Y P :=
  h.congr (fun _ ↦ h.measurable_obs 0) h.measurable_action h.measurable_feedback
    h.ae_obs_eq_obs_zero (fun _ ↦ .rfl) (fun _ ↦ .rfl)

end IsAlgEnvSeq

namespace IT

/-- A measure `P` on a measurable space that carries random variables `E`, `A`, and `Y` such that
`IsBayesAlgEnvSeq Q κ alg E A Y P`. The parameter is the observation of the first round,
`IT.obs 0`. -/
noncomputable
def bayesTrajMeasure (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨)
    [IsMarkovKernel κ] (alg : Algorithm Unit 𝓐 𝓨) : Measure (ℕ → Round 𝓔 𝓐 𝓨) :=
  trajMeasure (alg.comapObs (fun _ : 𝓔 ↦ ())) (bayesStationaryEnv Q κ)
deriving IsProbabilityMeasure

lemma isBayesAlgEnvSeq_bayesTrajMeasure [StandardBorelSpace 𝓔]
    (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨) [IsMarkovKernel κ]
    (alg : Algorithm Unit 𝓐 𝓨) :
    IsBayesAlgEnvSeq Q κ alg (obs 0) action feedback (bayesTrajMeasure Q κ alg) :=
  (isAlgEnvSeq_trajMeasure _ _).isBayesAlgEnvSeq

/-- A kernel that represents the posterior over `E` given the history before time `n`. -/
noncomputable
def bayesTrajMeasurePosterior [StandardBorelSpace 𝓔] [Nonempty 𝓔]
    (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨) [IsMarkovKernel κ]
    (alg : Algorithm Unit 𝓐 𝓨) (n : ℕ) : Kernel (Hist Unit 𝓐 𝓨 n) 𝓔 :=
  condDistrib (obs 0) (history (noObs _) action feedback n) (bayesTrajMeasure Q κ alg)
deriving IsMarkovKernel

/-- The posterior given the empty history is the prior. -/
lemma bayesTrajMeasurePosterior_zero [StandardBorelSpace 𝓔] [Nonempty 𝓔]
    (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨) [IsMarkovKernel κ]
    (alg : Algorithm Unit 𝓐 𝓨) :
    bayesTrajMeasurePosterior Q κ alg 0 = Kernel.const _ Q :=
  (isBayesAlgEnvSeq_bayesTrajMeasure Q κ alg).condDistrib_param_history_zero

end IT

end Learning
