/-
Copyright (c) 2025 Rémy Degenne. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Rémy Degenne, Paulo Rauber
-/
module

public import LeanMachineLearning.SequentialLearning.Algorithm

/-!
# Probability space for algorithm-environment interactions

For any algorithm and environment, we construct a probability space on which we can define
a sequence of random variables representing the actions and feedback generated by the interaction
of the algorithm and the environment.
The main ingredient of the construction is the Ionescu-Tulcea theorem.

## Main statements

* `isAlgEnvSeq_unique`: the law of the sequence of rounds generated by an
  algorithm-environment pair is unique: it does not depend on the probability space used.
  If `O₁`, `A₁`, `R₁` and `O₂`, `A₂`, `R₂` are two algorithm-environment sequences generated by the
  same algorithm-environment pair on probability spaces `(Ω, P)` and `(Ω', P')`, then
  `P.map (trajectory O₁ A₁ R₁) = P'.map (trajectory O₂ A₂ R₂)`.

-/

@[expose] public section

open MeasureTheory ProbabilityTheory Filter Real Finset

open scoped ENNReal NNReal

namespace Learning

variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- Measure on the sequence of rounds generated by the algorithm/environment. -/
noncomputable
def trajMeasure (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨) :
    Measure (ℕ → Round 𝓞 𝓐 𝓨) :=
  Kernel.trajMeasureFin (stepKernel alg env)
deriving IsProbabilityMeasure

namespace IT

/-- The round at step `n`. -/
def step (n : ℕ) (h : ℕ → Round 𝓞 𝓐 𝓨) : Round 𝓞 𝓐 𝓨 := h n

/-- `obs n` is the observation at time `n`. This is a random variable on the measurable space
`ℕ → Round 𝓞 𝓐 𝓨`. -/
def obs (n : ℕ) (h : ℕ → Round 𝓞 𝓐 𝓨) : 𝓞 := (h n).obs

/-- `action n` is the action pulled at time `n`. This is a random variable on the measurable space
`ℕ → Round 𝓞 𝓐 𝓨`. -/
def action (n : ℕ) (h : ℕ → Round 𝓞 𝓐 𝓨) : 𝓐 := (h n).action

/-- `feedback n` is the feedback at time `n`. This is a random variable on the measurable space
`ℕ → Round 𝓞 𝓐 𝓨`. -/
def feedback (n : ℕ) (h : ℕ → Round 𝓞 𝓐 𝓨) : 𝓨 := (h n).feedback

/-- `hist n` is the history before time `n`: the rounds at times `0, ..., n - 1`.
This is a random variable on the measurable space `ℕ → Round 𝓞 𝓐 𝓨`. -/
def hist (n : ℕ) (h : ℕ → Round 𝓞 𝓐 𝓨) : Hist 𝓞 𝓐 𝓨 n := fun i ↦ h i

lemma fst_comp_step (n : ℕ) : Prod.fst ∘ step (𝓞 := 𝓞) (𝓐 := 𝓐) (𝓨 := 𝓨) n = obs n := rfl

lemma history_obs_action_feedback (n : ℕ) :
    history (obs (𝓞 := 𝓞) (𝓐 := 𝓐) (𝓨 := 𝓨)) action feedback n = hist n := rfl

@[simp]
lemma hist_zero : hist (𝓞 := 𝓞) (𝓐 := 𝓐) (𝓨 := 𝓨) 0 = fun _ ↦ default := Unique.eq_default _

@[fun_prop]
lemma measurable_step (n : ℕ) : Measurable (step n (𝓞 := 𝓞) (𝓐 := 𝓐) (𝓨 := 𝓨)) := by
  unfold step; fun_prop

@[fun_prop]
lemma measurable_step_prod : Measurable (fun p : ℕ × (ℕ → Round 𝓞 𝓐 𝓨) ↦ step p.1 p.2) :=
  measurable_from_prod_countable_right fun n ↦ (by simp only; fun_prop)

@[fun_prop]
lemma measurable_obs (n : ℕ) : Measurable (obs n (𝓞 := 𝓞) (𝓐 := 𝓐) (𝓨 := 𝓨)) := by
  unfold obs; fun_prop

@[fun_prop]
lemma measurable_obs_prod : Measurable (fun p : ℕ × (ℕ → Round 𝓞 𝓐 𝓨) ↦ obs p.1 p.2) :=
  measurable_from_prod_countable_right fun n ↦ (by simp only; fun_prop)

@[fun_prop]
lemma measurable_action (n : ℕ) : Measurable (action n (𝓞 := 𝓞) (𝓐 := 𝓐) (𝓨 := 𝓨)) := by
  unfold action; fun_prop

@[fun_prop]
lemma measurable_action_prod : Measurable (fun p : ℕ × (ℕ → Round 𝓞 𝓐 𝓨) ↦ action p.1 p.2) :=
  measurable_from_prod_countable_right fun n ↦ (by simp only; fun_prop)

@[fun_prop]
lemma measurable_feedback (n : ℕ) : Measurable (feedback n (𝓞 := 𝓞) (𝓐 := 𝓐) (𝓨 := 𝓨)) := by
  unfold feedback; fun_prop

@[fun_prop]
lemma measurable_feedback_prod : Measurable (fun p : ℕ × (ℕ → Round 𝓞 𝓐 𝓨) ↦ feedback p.1 p.2) :=
  measurable_from_prod_countable_right fun n ↦ (by simp only; fun_prop)

@[fun_prop]
lemma measurable_hist (n : ℕ) : Measurable (hist n (𝓞 := 𝓞) (𝓐 := 𝓐) (𝓨 := 𝓨)) := by
  unfold hist; fun_prop

lemma hist_succ_eq_comp_frestrictLe (n : ℕ) :
    hist (𝓞 := 𝓞) (𝓐 := 𝓐) (𝓨 := 𝓨) (n + 1) =
      (MeasurableEquiv.finSuccPiIic (fun _ ↦ Round 𝓞 𝓐 𝓨) n).symm ∘ Preorder.frestrictLe n := rfl

lemma frestrictLe_eq_comp_hist (n : ℕ) :
    Preorder.frestrictLe («π» := fun _ ↦ Round 𝓞 𝓐 𝓨) n =
      (MeasurableEquiv.finSuccPiIic (fun _ ↦ Round 𝓞 𝓐 𝓨) n) ∘ hist (n + 1) := rfl

lemma step_eq_eval_comp_hist (n : ℕ) :
    step (𝓞 := 𝓞) (𝓐 := 𝓐) (𝓨 := 𝓨) n = (fun x ↦ x (Fin.last n)) ∘ (hist (n + 1)) := rfl

lemma obs_eq_eval_comp_hist (n : ℕ) :
    obs (𝓞 := 𝓞) (𝓐 := 𝓐) (𝓨 := 𝓨) n = (fun x ↦ (x (Fin.last n)).obs) ∘ (hist (n + 1)) := rfl

lemma action_eq_eval_comp_hist (n : ℕ) :
    action (𝓞 := 𝓞) (𝓐 := 𝓐) (𝓨 := 𝓨) n = (fun x ↦ (x (Fin.last n)).action) ∘ (hist (n + 1)) := rfl

lemma feedback_eq_eval_comp_hist (n : ℕ) :
    feedback (𝓞 := 𝓞) (𝓐 := 𝓐) (𝓨 := 𝓨) n =
      (fun x ↦ (x (Fin.last n)).feedback) ∘ (hist (n + 1)) := rfl

/-- The history before time `m` is a restriction of the history before time `n ≥ m`. -/
lemma hist_eq_comp_hist {m n : ℕ} (hmn : m ≤ n) :
    hist (𝓞 := 𝓞) (𝓐 := 𝓐) (𝓨 := 𝓨) m = (fun h (i : Fin m) ↦ h (Fin.castLE hmn i)) ∘ hist n := rfl

end IT

section ModelEquivalence

variable {Ω Ω' : Type*} {mΩ : MeasurableSpace Ω} {mΩ' : MeasurableSpace Ω'}
  {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨}
  {P : Measure Ω} [IsProbabilityMeasure P] {P' : Measure Ω'} [IsProbabilityMeasure P']
  {O₁ : ℕ → Ω → 𝓞} {A₁ : ℕ → Ω → 𝓐} {R₁ : ℕ → Ω → 𝓨}
  {O₂ : ℕ → Ω' → 𝓞} {A₂ : ℕ → Ω' → 𝓐} {R₂ : ℕ → Ω' → 𝓨} {N : ℕ}

lemma IsAlgEnvSeq.map_trajectory (h : IsAlgEnvSeq O₁ A₁ R₁ alg env P) :
    P.map (trajectory O₁ A₁ R₁) = trajMeasure alg env :=
  (Kernel.hasLaw_trajMeasureFin (X := fun _ ↦ Round 𝓞 𝓐 𝓨) (Y := step O₁ A₁ R₁) (P := P)
    (κ' := stepKernel alg env) h.measurable_step h.hasCondDistrib_step).map_eq

lemma IsAlgEnvSeq.hasLaw_trajectory (h : IsAlgEnvSeq O₁ A₁ R₁ alg env P) :
    HasLaw (trajectory O₁ A₁ R₁) (trajMeasure alg env) P where
  aemeasurable := h.measurable_trajectory.aemeasurable
  map_eq := h.map_trajectory

lemma IsAlgEnvSeqUntil.map_history (h : IsAlgEnvSeqUntil O₁ A₁ R₁ alg env P N) :
    P.map (history O₁ A₁ R₁ N) = (trajMeasure alg env).map (IT.hist N) :=
  Kernel.eq_trajMeasureFin_map (X := fun _ ↦ Round 𝓞 𝓐 𝓨) (Y := step O₁ A₁ R₁) (P := P) (N := N)
    (κ' := stepKernel alg env) h.measurable_step h.hasCondDistrib_step

lemma IsAlgEnvSeq.map_history (h : IsAlgEnvSeq O₁ A₁ R₁ alg env P) (n : ℕ) :
    P.map (history O₁ A₁ R₁ n) = (trajMeasure alg env).map (IT.hist n) :=
  (h.isAlgEnvSeqUntil n).map_history

/-- The law of the sequence of rounds generated by an algorithm-environment pair
is unique: it does not depend on the probability space used. -/
lemma isAlgEnvSeq_unique (h1 : IsAlgEnvSeq O₁ A₁ R₁ alg env P)
    (h2 : IsAlgEnvSeq O₂ A₂ R₂ alg env P') :
    P.map (trajectory O₁ A₁ R₁) = P'.map (trajectory O₂ A₂ R₂) := by
  rw [h1.map_trajectory, h2.map_trajectory]

/-- The law of the sequence of rounds generated by an algorithm-environment pair
is unique: it does not depend on the probability space used. -/
theorem IsAlgEnvSeq.identDistrib_trajectory (h1 : IsAlgEnvSeq O₁ A₁ R₁ alg env P)
    (h2 : IsAlgEnvSeq O₂ A₂ R₂ alg env P') :
    IdentDistrib (trajectory O₁ A₁ R₁) (trajectory O₂ A₂ R₂) P P' where
  aemeasurable_fst := h1.measurable_trajectory.aemeasurable
  aemeasurable_snd := h2.measurable_trajectory.aemeasurable
  map_eq := isAlgEnvSeq_unique h1 h2

/-- The law of the history before time `N` is determined by the algorithm-environment pair,
provided that the sequence is an algorithm-environment sequence until time `N`. -/
lemma isAlgEnvSeqUntil_unique (h1 : IsAlgEnvSeqUntil O₁ A₁ R₁ alg env P N)
    (h2 : IsAlgEnvSeqUntil O₂ A₂ R₂ alg env P' N) :
    P.map (history O₁ A₁ R₁ N) = P'.map (history O₂ A₂ R₂ N) := by
  rw [h1.map_history, h2.map_history]

end ModelEquivalence

namespace IT

/-- Filtration of the algorithm Seq: `IT.filtration 𝓞 𝓐 𝓨 n` is the σ-algebra generated by the
rounds at times `0, ..., n`, that is by `hist (n + 1)`. -/
protected def filtration (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐]
    [MeasurableSpace 𝓨] :
    Filtration ℕ (inferInstance : MeasurableSpace (ℕ → Round 𝓞 𝓐 𝓨)) :=
  MeasureTheory.Filtration.piLE (X := fun _ ↦ Round 𝓞 𝓐 𝓨)

lemma filtration_eq_comap (n : ℕ) :
    IT.filtration 𝓞 𝓐 𝓨 n = MeasurableSpace.comap (hist (n + 1)) inferInstance := by
  simp only [IT.filtration, Filtration.piLE_eq_comap_frestrictLe]
  refine le_antisymm ?_ ?_
  · rw [← measurable_iff_comap_le, frestrictLe_eq_comp_hist]
    exact measurable_comp_comap _ (by fun_prop)
  · rw [← measurable_iff_comap_le, hist_succ_eq_comp_frestrictLe]
    exact measurable_comp_comap _ (by fun_prop)

lemma adapted_step : Adapted (IT.filtration 𝓞 𝓐 𝓨) (step (𝓞 := 𝓞) (𝓐 := 𝓐) (𝓨 := 𝓨)) := by
  intro n
  rw [filtration_eq_comap, step_eq_eval_comp_hist]
  exact measurable_comp_comap _ (by fun_prop)

lemma adapted_obs : Adapted (IT.filtration 𝓞 𝓐 𝓨) obs := by
  intro n
  rw [filtration_eq_comap, obs_eq_eval_comp_hist]
  exact measurable_comp_comap _ (by fun_prop)

lemma measurable_hist_succ_filtration (n : ℕ) :
    Measurable[IT.filtration 𝓞 𝓐 𝓨 n] (hist (n + 1)) := by
  rw [filtration_eq_comap]
  exact measurable_iff_comap_le.mpr le_rfl

lemma adapted_hist : Adapted (IT.filtration 𝓞 𝓐 𝓨) hist := by
  intro n
  rw [filtration_eq_comap, hist_eq_comp_hist n.le_succ]
  exact measurable_comp_comap _ (by fun_prop)

lemma adapted_action : Adapted (IT.filtration 𝓞 𝓐 𝓨) action := by
  intro n
  rw [filtration_eq_comap, action_eq_eval_comp_hist]
  exact measurable_comp_comap _ (by fun_prop)

lemma adapted_feedback : Adapted (IT.filtration 𝓞 𝓐 𝓨) feedback := by
  intro n
  rw [filtration_eq_comap, feedback_eq_eval_comp_hist]
  exact measurable_comp_comap _ (by fun_prop)

section FiltrationAction

/-- Filtration generated by the history before time `n` together with the observation and the
action at time `n`. -/
def filtrationAction (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐]
    [MeasurableSpace 𝓨] :
    Filtration ℕ (inferInstance : MeasurableSpace (ℕ → Round 𝓞 𝓐 𝓨)) where
  seq n := MeasurableSpace.comap (fun ω ↦ ((hist n ω, obs n ω), action n ω)) inferInstance
  mono' n m hnm := by
    simp only
    rw [← measurable_iff_comap_le]
    rcases eq_or_lt_of_le hnm with rfl | hlt
    · exact measurable_iff_comap_le.mpr le_rfl
    have : (fun ω ↦ ((hist (𝓞 := 𝓞) (𝓐 := 𝓐) (𝓨 := 𝓨) n ω, obs n ω), action n ω)) =
        (fun p : (Hist 𝓞 𝓐 𝓨 m × 𝓞) × 𝓐 ↦
          ((fun i : Fin n ↦ p.1.1 (Fin.castLE hnm i), (p.1.1 ⟨n, hlt⟩).obs),
            (p.1.1 ⟨n, hlt⟩).action)) ∘
        (fun ω ↦ ((hist m ω, obs m ω), action m ω)) := rfl
    rw [this]
    exact measurable_comp_comap _ (by fun_prop)
  le' n := by
    rw [← measurable_iff_comap_le]
    fun_prop

lemma filtrationAction_eq_comap (n : ℕ) :
    filtrationAction 𝓞 𝓐 𝓨 n =
      MeasurableSpace.comap (fun ω ↦ ((hist n ω, obs n ω), action n ω)) inferInstance := rfl

lemma filtrationAction_zero_eq_comap :
    filtrationAction 𝓞 𝓐 𝓨 0 =
      MeasurableSpace.comap (fun ω ↦ (obs 0 ω, action 0 ω)) inferInstance := by
  rw [filtrationAction_eq_comap, hist_zero]
  refine le_antisymm ?_ ?_
  · rw [← measurable_iff_comap_le]
    exact (measurable_const.prodMk
      (measurable_fst.comp (measurable_iff_comap_le.mpr le_rfl))).prodMk
      (measurable_snd.comp (measurable_iff_comap_le.mpr le_rfl))
  · rw [← measurable_iff_comap_le]
    exact ((measurable_snd.comp measurable_fst).comp
      (measurable_iff_comap_le.mpr le_rfl)).prodMk
      (measurable_snd.comp (measurable_iff_comap_le.mpr le_rfl))

lemma measurable_hist_filtrationAction (n : ℕ) :
    Measurable[filtrationAction 𝓞 𝓐 𝓨 n] (hist n) :=
  (measurable_fst.comp measurable_fst).comp (measurable_iff_comap_le.mpr le_rfl)

lemma filtration_le_filtrationAction_add_one (n : ℕ) :
    IT.filtration 𝓞 𝓐 𝓨 n ≤ filtrationAction 𝓞 𝓐 𝓨 (n + 1) := by
  rw [filtration_eq_comap]
  exact measurable_iff_comap_le.mp (measurable_hist_filtrationAction (n + 1))

lemma filtration_le_filtrationAction {m n : ℕ} (h : n < m) :
    IT.filtration 𝓞 𝓐 𝓨 n ≤ filtrationAction 𝓞 𝓐 𝓨 m := by
  have h' : n + 1 ≤ m := by grind
  exact (filtration_le_filtrationAction_add_one n).trans ((filtrationAction 𝓞 𝓐 𝓨).mono h')

lemma filtrationAction_le_filtration_self (n : ℕ) :
    filtrationAction 𝓞 𝓐 𝓨 n ≤ IT.filtration 𝓞 𝓐 𝓨 n := by
  rw [filtrationAction_eq_comap, ← measurable_iff_comap_le]
  exact ((adapted_hist n).prodMk (adapted_obs n)).prodMk (adapted_action n)

lemma filtrationAction_le_filtration {m n : ℕ} (h : m ≤ n) :
    filtrationAction 𝓞 𝓐 𝓨 m ≤ IT.filtration 𝓞 𝓐 𝓨 n :=
  (filtrationAction_le_filtration_self m).trans ((IT.filtration 𝓞 𝓐 𝓨).mono h)

lemma measurable_obs_filtrationAction (n : ℕ) :
    Measurable[filtrationAction 𝓞 𝓐 𝓨 n] (obs n) :=
  (measurable_snd.comp measurable_fst).comp (measurable_iff_comap_le.mpr le_rfl)

lemma measurable_action_filtrationAction (n : ℕ) :
    Measurable[filtrationAction 𝓞 𝓐 𝓨 n] (action n) :=
  measurable_snd.comp (measurable_iff_comap_le.mpr le_rfl)

end FiltrationAction

section Laws

lemma hasCondDistrib_step (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨) (n : ℕ) :
    HasCondDistrib (step n) (hist n) (stepKernel alg env n) (trajMeasure alg env) :=
  Kernel.hasCondDistrib_trajMeasureFin n

lemma hasCondDistrib_obs (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨) (n : ℕ) :
    HasCondDistrib (obs n) (hist n) (env.obs n) (trajMeasure alg env) := by
  rw [← fst_comp_step, ← fst_stepKernel, Kernel.fst_eq]
  exact HasCondDistrib.comp_left (hasCondDistrib_step alg env n) measurable_fst

/-- The action and the feedback at time `n`, given the history and the observation at time `n`. -/
lemma hasCondDistrib_action_feedback (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨) (n : ℕ) :
    HasCondDistrib (fun ω ↦ (action n ω, feedback n ω)) (fun ω ↦ (hist n ω, obs n ω))
      (alg.policy n ⊗ₖ env.feedback n) (trajMeasure alg env) :=
  HasCondDistrib.of_compProd (hasCondDistrib_step alg env n)

lemma hasCondDistrib_action (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨) (n : ℕ) :
    HasCondDistrib (action n) (fun ω ↦ (hist n ω, obs n ω)) (alg.policy n)
      (trajMeasure alg env) := by
  have h := (hasCondDistrib_action_feedback alg env n).fst
  rwa [Kernel.fst_compProd] at h

lemma hasCondDistrib_feedback (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨) (n : ℕ) :
    HasCondDistrib (feedback n) (fun ω ↦ ((hist n ω, obs n ω), action n ω)) (env.feedback n)
      (trajMeasure alg env) :=
  HasCondDistrib.of_compProd (hasCondDistrib_action_feedback alg env n)

lemma isAlgEnvSeq_trajMeasure (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨) :
    IsAlgEnvSeq obs action feedback alg env (trajMeasure alg env) where
  hasCondDistrib_obs n := hasCondDistrib_obs alg env n
  hasCondDistrib_action n := hasCondDistrib_action alg env n
  hasCondDistrib_feedback n := hasCondDistrib_feedback alg env n

lemma hasLaw_step_zero (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨) :
    HasLaw (step 0) (env.obs0 ⊗ₘ (alg.p0 ⊗ₖ env.ν0)) (trajMeasure alg env) :=
  (isAlgEnvSeq_trajMeasure alg env).hasLaw_step_zero

lemma hasLaw_obs_zero (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨) :
    HasLaw (obs 0) env.obs0 (trajMeasure alg env) :=
  (isAlgEnvSeq_trajMeasure alg env).hasLaw_obs_zero

lemma hasCondDistrib_action_zero (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨) :
    HasCondDistrib (action 0) (obs 0) alg.p0 (trajMeasure alg env) :=
  (isAlgEnvSeq_trajMeasure alg env).hasCondDistrib_action_zero

lemma hasCondDistrib_feedback_zero (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨) :
    HasCondDistrib (feedback 0) (fun ω ↦ (obs 0 ω, action 0 ω)) env.ν0 (trajMeasure alg env) :=
  (isAlgEnvSeq_trajMeasure alg env).hasCondDistrib_feedback_zero

end Laws

end IT

end Learning
