name = "LeanMachineLearning"
defaultTargets = ["LeanMachineLearning"]
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
# Enable all mathlib linters: automatically matches what mathlib uses.
weak.linter.mathlibStandardSet = true

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "9ae96ab97edd1c2aab1325e687da235f9c628e8e"

[[lean_lib]]
name = "LeanMachineLearning"

[[lean_lib]]
name = "LMLTutorial"
globs = ["LMLTutorial.*"]

[[lean_exe]]
name = "tutorial"
srcDir = "LMLTutorial/"
root = "Tutorial"
