name = "LeanMachineLearning"
defaultTargets = ["LeanMachineLearning"]
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
# Enable all mathlib linters: automatically matches what mathlib uses.
weak.linter.mathlibStandardSet = true

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "aaedc74a09fbe1da58b11cf4d27806a6fa1a86eb"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "LeanMachineLearning"

[[lean_lib]]
name = "LMLTutorial"
globs = ["LMLTutorial.*"]

[[lean_exe]]
name = "tutorial"
srcDir = "LMLTutorial/"
root = "Tutorial"
