/-
Copyright (c) 2026 LML Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: LML Contributors
-/
module

public import LeanMachineLearning.Optimization.NTK.Basic
public import LeanMachineLearning.Optimization.NTK.Kernel
public import Mathlib.Probability.Distributions.Gaussian.Multivariate
public import Mathlib.Probability.Distributions.Gaussian.Real
public import Mathlib.Probability.Distributions.Gaussian.Basic
public import Mathlib.Probability.Distributions.Gaussian.CharFun
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.Probability.ProductMeasure
public import Mathlib.Probability.StrongLaw
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.LinearAlgebra.Matrix.PosDef
public import Mathlib.MeasureTheory.Measure.LevyConvergence
public import Mathlib.MeasureTheory.Function.ConvergenceInDistribution


/-!
# NTK Initialization and Exact Finite-Width Conditional Distribution

This file formalizes the parameter initialization probability space, mutual independence
structure, Theorem 1 (Exact Conditional Normality), and Theorem 2 (Strong Law of Large Numbers
for the Covariance Tensor / Asymptotic NNGP Limit) for neural networks.

## Mathematical Formulation

* **Initialization Probability Space and Independence Structure**:
  * Underlying parameter space `(Fin n → Fin d → ℝ) × (Fin n → ℝ)` with product
    measure `initMeasure n d = (gaussianInit n d).prod (gaussianReadoutMeasure n)`.
  * Readout weights: $a_i \stackrel{\text{i.i.d.}}{\sim} \mathcal{N}(0, 1) \quad \forall i$.
  * Input weights:
    $\mathbf{w}_i \stackrel{\text{i.i.d.}}{\sim} \mathcal{N}(\mathbf{0}, \mathbf{I}_{n_0})$.
  * Mutual Independence: $\{a_i\}_{i=1}^n$ is mutually independent of $\{\mathbf{w}_i\}_{i=1}^n$,
    and pairs $(a_i, \mathbf{w}_i)$ are independent across hidden unit indices.

* **Theorem 1 (Exact Conditional Normality)**:
  * Conditional on the sub-$\sigma$-algebra $\mathcal{F}$ generated by input weights $\mathbf{W}$,
    the output vector
    $\mathbf{f}_m := (f(\mathbf{x}^1; \boldsymbol{\theta}), \dots,
      f(\mathbf{x}^m; \boldsymbol{\theta}))^\top$
    is an exact centered multivariate Gaussian vector:
    $$\mathbf{f}_m \mid \mathcal{F} \sim \mathcal{N}\left(\mathbf{0},
      \boldsymbol{\Phi}^{(n)}\right)$$
    where the empirical covariance matrix entries are:
    $$\Phi^{(n), \alpha \beta} := \frac{1}{n} \sum_{i=1}^n \varphi(h_i(\mathbf{x}^\alpha))
      \varphi(h_i(\mathbf{x}^\beta)).$$

* **Proof Steps for Theorem 1**:
  * Step 1: For any projection vector $\mathbf{c} \in \mathbb{R}^m$, the scalar projection is
    $$\sum_{\alpha=1}^m c_\alpha f(\mathbf{x}^\alpha; \boldsymbol{\theta}) =
      \sum_{i=1}^n a_i \psi_i$$
    where $\psi_i := \frac{1}{\sqrt{n}} \sum_{\alpha=1}^m c_\alpha \varphi(h_i(\mathbf{x}^\alpha))$.
  * Step 2: $\psi_i$ is $\mathcal{F}$-measurable, so conditional on $\mathcal{F}$ the coefficients
    $\psi_i$ are deterministic constants.
  * Step 3: $\{a_i\}_{i=1}^n$ are independent of $\mathcal{F}$ and i.i.d. standard Gaussian; thus
    $\sum_{i=1}^n a_i \psi_i$ is a linear combination of independent zero-mean Gaussians.
  * Step 4: The variance of the linear combination is
    $$\sum_{i=1}^n \psi_i^2 = \mathbf{c}^\top \boldsymbol{\Phi}^{(n)} \mathbf{c}.$$
  * Step 5: By Cramér-Wold / linear functional characterization of Gaussianity, every 1D projection
    is $\mathcal{N}(0, \mathbf{c}^\top \boldsymbol{\Phi}^{(n)} \mathbf{c})$, so the conditional
    joint distribution is $\mathcal{N}(\mathbf{0}, \boldsymbol{\Phi}^{(n)})$.

* **Theorem 2 (Strong Law of Large Numbers for the Covariance Tensor / Asymptotic NNGP Limit)**:
  * As width $n \to \infty$, the empirical covariance matrix converges almost surely to the
    deterministic NNGP Gram matrix:
    $$\Phi^{(n), \alpha \beta} \xrightarrow{\text{a.s.}}
      \int \varphi(\mathbf{w} \odot \mathbf{x}^\alpha) \varphi(\mathbf{w} \odot \mathbf{x}^\beta)
      d\mathcal{N}(\mathbf{0}, \mathbf{I})$$
  * Full matrix convergence:
    $\boldsymbol{\Phi}^{(n)} \xrightarrow{\text{a.s.}} \boldsymbol{\Phi}$
    in $\mathbb{R}^{m \times m}$.

* **Proof Steps for Theorem 2**:
  * Step 1: For fixed inputs $\mathbf{x}^\alpha, \mathbf{x}^\beta$,
    define the scalar random variables
    $Y_i := \varphi(h_i(\mathbf{x}^\alpha)) \varphi(h_i(\mathbf{x}^\beta))$ for
    $i \in \{1, \dots, n\}$.
  * Step 2: Because $\{\mathbf{w}_i\}_{i=1}^n$ are i.i.d., the sequence $\{Y_i\}_{i=1}^n$
    is independent and identically distributed.
  * Step 3: By square-integrability of $\varphi$ and Cauchy-Schwarz,
    the expectation exists and is finite:
    $$\mathbb{E}_{\mathbf{w}_i}\left[ |Y_i| \right] \le
      \sqrt{\mathbb{E}_{\mathbf{w}_i}[\varphi(h_i(\mathbf{x}^\alpha))^2]
      \mathbb{E}_{\mathbf{w}_i}[\varphi(h_i(\mathbf{x}^\beta))^2]} < \infty$$
  * Step 4: By Kolmogorov's Strong Law of Large Numbers (SLLN):
    $$\Phi^{(n), \alpha \beta} = \frac{1}{n} \sum_{i=1}^n Y_i
      \xrightarrow{\text{a.s.}} \mathbb{E}_{\mathbf{w}}[Y_1]$$

## Main definitions and theorems

* `NTK.gaussianReadoutMeasure` : transparent product measure $\bigotimes_{i=1}^n \mathcal{N}(0, 1)$.
* `NTK.initMeasure` : joint initialization product measure on parameters.
* `NTK.evalSingle` : scalar network output $f(\mathbf{x}; \mathbf{W}, a)$.
* `NTK.evalSingle_eq_normalized_sum` : equation lemma for scalar network evaluation.
* `NTK.evalVector` : output vector $\mathbf{f}_m(\mathbf{W}, a)$.
* `NTK.empiricalCovariance` : empirical covariance matrix $\boldsymbol{\Phi}^{(n)}$.
* `NTK.psi` : projection coefficients $\psi_i$.
* `NTK.psi_eq_normalized_sum`, `NTK.psi_sq`, `NTK.psi_measurable` : equation,
  square-expansion, and measurability API for `psi`.
* `NTK.projection_eq_sum_psi` : Step 1 algebraic identity.
* `NTK.sum_psi_sq_eq_bilin` : Step 4 variance identity
  $\sum_i \psi_i^2 = \mathbf{c}^\top \boldsymbol{\Phi}^{(n)} \mathbf{c}$.
* `NTK.empiricalCovariance_posSemidef` : positive semidefiniteness of $\boldsymbol{\Phi}^{(n)}$.
* `NTK.map_readout_projection_eq_gaussianReal` : Step 4 1D conditional normality.
* `NTK.exact_conditional_normality` : Theorem 1 (multivariate conditional normality).
* `NTK.empiricalCovariance_tendsto_integral` : Theorem 2 entrywise almost sure convergence.
* `NTK.empiricalCovariance_tendsto_matrix_integral` : Theorem 2 matrix almost sure convergence.
* `NTK.outputMeasure`, `NTK.outputMeasure_eq_map` : unconditional output law and its
  pushforward API.
* `NTK.charFun_outputMeasure` : total-expectation formula for the unconditional
  characteristic function.
-/

@[expose] public section

set_option linter.style.longLine false

open Real MeasureTheory ProbabilityTheory Matrix Complex
open scoped BigOperators MatrixOrder RealInnerProductSpace

namespace NTK

variable {d n m : ℕ}

section Preliminaries

/-! ## Network Setup and Initialization Probability Space -/

/-! ### Network Evaluation and Empirical Covariance -/

/-- Single-output evaluation of a two-layer neural network with width `n`, activation `φ`,
input weights `W`, and readout weights `a`:
  `f(x; W, a) = (1/√n) ∑ i, a i * φ (W i ⊙ x)`. -/
noncomputable def evalSingle
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (a : Fin n → ℝ) (x : Fin d → ℝ) : ℝ :=
  (n : ℝ)⁻¹.sqrt * ∑ i : Fin n, a i * φ (W i ⊙ x)

/-- The normalized-sum formula for a scalar network evaluation. This is the public
equation lemma for `evalSingle`, so proofs need not unfold its implementation. -/
lemma evalSingle_eq_normalized_sum
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (a : Fin n → ℝ) (x : Fin d → ℝ) :
    evalSingle φ W a x = (n : ℝ)⁻¹.sqrt * ∑ i : Fin n, a i * φ (W i ⊙ x) := rfl

/-- The output vector `f_m(W, a) ∈ ℝᵐ` evaluated at `m` input points `X 0, …, X (m - 1)`:
  `f_m(W, a)_α = f(X α; W, a)`. -/
noncomputable def evalVector
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (a : Fin n → ℝ) (X : Fin m → Fin d → ℝ) :
    EuclideanSpace ℝ (Fin m) :=
  WithLp.toLp 2 (fun α => evalSingle φ W a (X α))

/-- The empirical covariance matrix `Φ^{(n)} ∈ ℝ^{m × m}`:
  `Φ^{(n), α β} = (1/n) ∑ i, φ (W i ⊙ X α) * φ (W i ⊙ X β)`. -/
noncomputable def empiricalCovariance
    (n : ℕ) (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) :
    Matrix (Fin m) (Fin m) ℝ :=
  fun α β => (n : ℝ)⁻¹ * ∑ i : Fin n, φ (W i ⊙ X α) * φ (W i ⊙ X β)

/-! ### API for Network Evaluation -/

@[simp] lemma evalVector_ofLp
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (a : Fin n → ℝ) (X : Fin m → Fin d → ℝ) (α : Fin m) :
    (evalVector φ W a X).ofLp α = evalSingle φ W a (X α) := rfl

lemma evalVector_inner
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (a : Fin n → ℝ) (t : EuclideanSpace ℝ (Fin m)) :
    ⟪t, evalVector φ W a X⟫ = ∑ α : Fin m, t.ofLp α * evalSingle φ W a (X α) := by
  simp only [evalVector, PiLp.inner_apply, RCLike.inner_apply', conj_trivial]

lemma evalVector_continuous
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) :
    Continuous (fun a => evalVector φ W a X) := by
  change Continuous ((WithLp.toLp 2) ∘ (fun a α => evalSingle φ W a (X α)))
  refine (PiLp.continuous_toLp 2 _).comp (continuous_pi fun α => ?_)
  simp only [evalSingle_eq_normalized_sum]
  exact continuous_const.mul (continuous_finsetSum _ fun i _ =>
    (continuous_apply i).mul continuous_const)

lemma evalVector_measurable
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) :
    Measurable (fun a => evalVector φ W a X) :=
  (evalVector_continuous φ W X).measurable

lemma inner_evalVector_continuous
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (t : EuclideanSpace ℝ (Fin m)) :
    Continuous (fun a => ⟪t, evalVector φ W a X⟫) :=
  (innerSL ℝ t).continuous.comp (evalVector_continuous φ W X)

lemma inner_evalVector_measurable
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (t : EuclideanSpace ℝ (Fin m)) :
    Measurable (fun a => ⟪t, evalVector φ W a X⟫) :=
  (inner_evalVector_continuous φ W X t).measurable

/-! ### Initialization Probability Space and Independence Structure -/

/-- Transparent readout weight product measure on `Fin n → ℝ` with i.i.d. coordinates $\mathcal{N}(0, 1)$. -/
noncomputable abbrev gaussianReadoutMeasure (n : ℕ) : Measure (Fin n → ℝ) :=
  Measure.pi (fun _ : Fin n => gaussianReal 0 1)

/-- Instance: `gaussianInit n d` from `Basic.lean` is a probability measure. -/
instance instIsProbabilityMeasureGaussianInit (n d : ℕ) :
    IsProbabilityMeasure (gaussianInit n d) := by
  dsimp [gaussianInit]
  infer_instance

/-- Transparent joint initialization measure on `(Fin n → Fin d → ℝ) × (Fin n → ℝ)`
using the existing `NTK.gaussianInit` from `Basic.lean`. -/
noncomputable abbrev initMeasure (n d : ℕ) : Measure ((Fin n → Fin d → ℝ) × (Fin n → ℝ)) :=
  (gaussianInit n d).prod (gaussianReadoutMeasure n)

/-- Readout weight coordinates `a_i` have marginal standard normal distribution $\mathcal{N}(0, 1)$. -/
lemma map_gaussianReadoutMeasure_coord (i : Fin n) :
    Measure.map (fun a : Fin n → ℝ => a i) (gaussianReadoutMeasure n) = gaussianReal 0 1 :=
  (MeasureTheory.measurePreserving_eval (fun _ : Fin n => gaussianReal 0 1) i).map_eq

/-- Readout weights `a_i` are mutually independent across hidden units `i ∈ Fin n`. -/
lemma iIndepFun_readoutWeights (n : ℕ) :
    iIndepFun (fun i : Fin n => fun a : Fin n → ℝ => a i) (gaussianReadoutMeasure n) :=
  iIndepFun_pi (fun _ => aemeasurable_id)

/-- Input weight rows `W_i` have marginal standard Gaussian row distribution `𝒩(0, Iᵈ)`. -/
lemma map_gaussianInit_row (i : Fin n) :
    Measure.map (fun W : Fin n → Fin d → ℝ => W i) (gaussianInit n d) = gaussianRowMeasure d :=
  (MeasureTheory.measurePreserving_eval (fun _ : Fin n => gaussianRowMeasure d) i).map_eq

/-- Input weight rows `W_i` are mutually independent across hidden unit indices `i ∈ Fin n`. -/
lemma iIndepFun_inputWeights (n d : ℕ) :
    iIndepFun (fun i : Fin n => fun W : Fin n → Fin d → ℝ => W i) (gaussianInit n d) :=
  iIndepFun_pi (fun _ => aemeasurable_id)

/-- Mutual Independence: the family of input weights `W` is independent of readout weights `a`. -/
lemma indepFun_input_readout (n d : ℕ) :
    IndepFun (fun p : (Fin n → Fin d → ℝ) × (Fin n → ℝ) => p.1)
      (fun p : (Fin n → Fin d → ℝ) × (Fin n → ℝ) => p.2)
      (initMeasure n d) :=
  indepFun_prod measurable_id measurable_id

end Preliminaries

section Theorem1

/-! ## Theorem 1: Exact Finite-Width Conditional Normality -/

/-! ### Step 1 & Step 2: Linear Projections and ψ Coefficients -/

/-- The $\mathcal{F}$-measurable coefficients `ψ_i` for each hidden unit `i`:
  `ψ_i = (1/√n) ∑_α c_α φ(W i ⊙ X α)`. -/
noncomputable def psi
    (n : ℕ) (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (c : Fin m → ℝ) (i : Fin n) : ℝ :=
  (n : ℝ)⁻¹.sqrt * ∑ α : Fin m, c α * φ (W i ⊙ X α)

/-- The normalized-sum formula for a projection coefficient. This is the public
equation lemma for `psi`, so proofs need not unfold its implementation. -/
lemma psi_eq_normalized_sum
    (n : ℕ) (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (c : Fin m → ℝ) (i : Fin n) :
    psi n φ W X c i = (n : ℝ)⁻¹.sqrt * ∑ α : Fin m, c α * φ (W i ⊙ X α) := rfl

/-- For measurable `φ`, each projection coefficient is measurable as a function of the input
weight matrix. This formalizes the `ℱ`-measurability assertion in Step 2. -/
lemma psi_measurable
    (n : ℕ) (φ : ℝ → ℝ) (hφ : Measurable φ) (X : Fin m → Fin d → ℝ)
    (c : Fin m → ℝ) (i : Fin n) :
    Measurable (fun W : Fin n → Fin d → ℝ => psi n φ W X c i) := by
  simp_rw [psi_eq_normalized_sum]
  refine Measurable.const_mul (Finset.measurable_sum _ fun α _ => ?_) _
  exact measurable_const.mul
    (hφ.comp ((measurable_innerProduct_left (X α)).comp (measurable_pi_apply i)))

/-- **Step 1 (Linear projection identity)**:
For any linear combination vector `c : Fin m → ℝ`, the scalar linear projection of
the network output satisfies:
  `∑ α, c α * f(X α; W, a) = ∑ i, a i * ψ_i`. -/
lemma projection_eq_sum_psi
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (a : Fin n → ℝ)
    (X : Fin m → Fin d → ℝ) (c : Fin m → ℝ) :
    (∑ α : Fin m, c α * evalSingle φ W a (X α)) =
      ∑ i : Fin n, a i * psi n φ W X c i :=
  calc
    (∑ α : Fin m, c α * evalSingle φ W a (X α)) =
        ∑ α : Fin m, c α * ((n : ℝ)⁻¹.sqrt *
          ∑ i : Fin n, a i * φ (W i ⊙ X α)) := by
      simp_rw [evalSingle_eq_normalized_sum]
    _ = ∑ i : Fin n, a i * ((n : ℝ)⁻¹.sqrt *
          ∑ α : Fin m, c α * φ (W i ⊙ X α)) := by
      simp_rw [Finset.mul_sum]
      rw [Finset.sum_comm]
      apply Finset.sum_congr rfl
      intro i _
      apply Finset.sum_congr rfl
      intro α _
      ring
    _ = ∑ i : Fin n, a i * psi n φ W X c i := by
      simp_rw [psi_eq_normalized_sum]

/-! ### Step 4: Variance and Positive Semidefiniteness -/

/-- The square of a projection coefficient expanded as a double sum. -/
lemma psi_sq (n : ℕ) (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ)
    (X : Fin m → Fin d → ℝ) (c : Fin m → ℝ) (i : Fin n) :
    (psi n φ W X c i) ^ 2 =
      (n : ℝ)⁻¹ * ∑ α : Fin m, ∑ β : Fin m,
        c α * c β * (φ (W i ⊙ X α) * φ (W i ⊙ X β)) :=
  calc
    (psi n φ W X c i) ^ 2 =
        ((n : ℝ)⁻¹.sqrt * ∑ α : Fin m, c α * φ (W i ⊙ X α)) ^ 2 := by
      rw [psi_eq_normalized_sum]
    _ = (n : ℝ)⁻¹ * (∑ α : Fin m, c α * φ (W i ⊙ X α)) ^ 2 := by
      rw [mul_pow, Real.sq_sqrt (by positivity)]
    _ = (n : ℝ)⁻¹ * ∑ α : Fin m, ∑ β : Fin m,
        c α * c β * (φ (W i ⊙ X α) * φ (W i ⊙ X β)) := by
      congr 1
      rw [sq, Finset.sum_mul_sum]
      apply Finset.sum_congr rfl
      intro α _
      apply Finset.sum_congr rfl
      intro β _
      ring

/-- **Step 4 (Variance identity)**:
The sum of squared coefficients `∑ i, ψ_i^2` equals the quadratic form
`c ⬝ᵥ Φ^{(n)} *ᵥ c`:
  `∑ i, ψ_i^2 = c ⬝ᵥ Φ^{(n)} *ᵥ c`. -/
lemma sum_psi_sq_eq_bilin
    (n : ℕ) (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (c : Fin m → ℝ) :
    ∑ i : Fin n, (psi n φ W X c i) ^ 2 =
      c ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ c := by
  simp_rw [psi_sq]
  simp only [dotProduct, mulVec, empiricalCovariance]
  simp_rw [Finset.mul_sum]
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro α _
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro β _
  calc
    (∑ i : Fin n, (n : ℝ)⁻¹ *
        (c α * c β * (φ (W i ⊙ X α) * φ (W i ⊙ X β)))) =
        ∑ i : Fin n, c α * ((n : ℝ)⁻¹ * (φ (W i ⊙ X α) * φ (W i ⊙ X β))) * c β := by
      apply Finset.sum_congr rfl
      intro i _
      ring
    _ = c α * ((∑ i : Fin n, (n : ℝ)⁻¹ *
        (φ (W i ⊙ X α) * φ (W i ⊙ X β))) * c β) := by
      rw [Finset.sum_mul, Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro i _
      ring

/-- The empirical covariance matrix `Φ^{(n)}` is symmetric (Hermitian). -/
lemma empiricalCovariance_isHermitian
    (n : ℕ) (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) :
    (empiricalCovariance n φ W X).IsHermitian := by
  ext α β
  simp only [empiricalCovariance, conjTranspose_apply, star_trivial]
  congr 1
  apply Finset.sum_congr rfl
  intro i _
  ring

/-- The quadratic form with `Φ^{(n)}` is always nonnegative. -/
lemma empiricalCovariance_nonneg
    (n : ℕ) (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (c : Fin m → ℝ) :
    0 ≤ c ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ c := by
  rw [← sum_psi_sq_eq_bilin]
  exact Finset.sum_nonneg (fun i _ => sq_nonneg (psi n φ W X c i))

/-- Finitely supported sum on a finite type coincides with universal sum when vanishing at zero. -/
private lemma finsupp_sum_eq_sum_univ {α β γ : Type*} [Fintype α] [Zero β] [AddCommMonoid γ]
    (x : α →₀ β) (f : α → β → γ) (hf : ∀ i, f i 0 = 0) :
    x.sum f = ∑ i : α, f i (x i) := by
  rw [Finsupp.sum, Finset.sum_subset (Finset.subset_univ x.support)]
  · intro i _ hi
    simp only [Finsupp.mem_support_iff, not_not] at hi
    rw [hi, hf]

/-- A real Hermitian matrix whose matrix quadratic form is nonnegative is positive semidefinite.
This bridges the function-vector API used by covariance proofs and the Finsupp-based definition. -/
private lemma posSemidef_of_bilin_nonneg
    (M : Matrix (Fin m) (Fin m) ℝ)
    (hM : M.IsHermitian)
    (h_nonneg : ∀ c : Fin m → ℝ, 0 ≤ c ⬝ᵥ M *ᵥ c) :
    M.PosSemidef := by
  refine ⟨hM, fun x => ?_⟩
  simp only [star_trivial]
  rw [finsupp_sum_eq_sum_univ _ _ (fun _ => by simp)]
  have h_inner (i : Fin m) : (x.sum fun j xj ↦ x i * M i j * xj) =
      ∑ j : Fin m, x i * M i j * x j := by
    rw [finsupp_sum_eq_sum_univ _ _ (fun _ => by simp)]
  simp_rw [h_inner]
  have h_dot : (∑ i : Fin m, ∑ j : Fin m, x i * M i j * x j) =
      (fun i => x i) ⬝ᵥ M *ᵥ (fun i => x i) := by
    rw [Finset.sum_comm, ← Matrix.dot_mulVec_eq_sum_sum]
  rw [h_dot]
  exact h_nonneg (fun i => x i)

/-- The empirical covariance matrix `Φ^{(n)}` is positive semidefinite (`PosSemidef`). -/
theorem empiricalCovariance_posSemidef
    (n : ℕ) (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) :
    (empiricalCovariance n φ W X).PosSemidef :=
  posSemidef_of_bilin_nonneg _ (empiricalCovariance_isHermitian n φ W X)
    (empiricalCovariance_nonneg n φ W X)

/-! ### Step 3, 4 & 5: Conditional Distribution and Theorem 1 -/

/-- Pushforward of the readout measure under standard inner product with a vector `v : Fin n → ℝ`
is a 1D Gaussian with mean 0 and variance `∑ i, v i ^ 2`. -/
lemma map_gaussianReadoutMeasure_inner (v : Fin n → ℝ) :
    Measure.map (fun a : Fin n → ℝ => ∑ i : Fin n, a i * v i) (gaussianReadoutMeasure n) =
      gaussianReal 0 (Real.toNNReal (∑ i : Fin n, v i ^ 2)) := by
  have h_eq : (fun a : Fin n → ℝ => ∑ i : Fin n, a i * v i) =
      (fun (u : EuclideanSpace ℝ (Fin n)) => innerSL ℝ (WithLp.toLp 2 v) u) ∘ (WithLp.toLp 2) := by
    ext a
    dsimp [innerSL_apply_apply]
    rw [EuclideanSpace.inner_toLp_toLp]
    simp [dotProduct, mul_comm]
  rw [h_eq, ← Measure.map_map]
  · have h_toLp : Measure.map (WithLp.toLp 2) (gaussianReadoutMeasure n) =
        stdGaussian (EuclideanSpace ℝ (Fin n)) := map_pi_eq_stdGaussian
    rw [h_toLp]
    have h_map := IsGaussian.map_eq_gaussianReal
      (μ := stdGaussian (EuclideanSpace ℝ (Fin n))) (innerSL ℝ (WithLp.toLp 2 v))
    rw [h_map]
    have h_mean : ∫ (u : EuclideanSpace ℝ (Fin n)),
        (innerSL ℝ (WithLp.toLp 2 v)) u ∂stdGaussian (EuclideanSpace ℝ (Fin n)) = 0 := by
      rw [(innerSL ℝ (WithLp.toLp 2 v)).integral_comp_id_comm IsGaussian.integrable_id]
      rw [integral_id_stdGaussian]
      exact map_zero (innerSL ℝ (WithLp.toLp 2 v))
    have h_var : Var[innerSL ℝ (WithLp.toLp 2 v); stdGaussian (EuclideanSpace ℝ (Fin n))] =
        ∑ i : Fin n, v i ^ 2 := by
      rw [variance_dual_stdGaussian]
      rw [innerSL_apply_norm]
      simp only [EuclideanSpace.real_norm_sq_eq]
    rw [h_mean, h_var]
  all_goals fun_prop

/-- **Step 4 (Exact 1D Conditional Normality)**:
Conditional on `W`, every scalar linear projection `∑ α, c α * f(X α; W, a)` is distributed
as a univariate centered Gaussian with variance `c ⬝ᵥ Φ^{(n)} *ᵥ c`. -/
theorem map_readout_projection_eq_gaussianReal
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) (c : Fin m → ℝ) :
    Measure.map (fun a => ∑ α : Fin m, c α * evalSingle φ W a (X α)) (gaussianReadoutMeasure n) =
      gaussianReal 0 (Real.toNNReal (c ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ c)) := by
  calc
    Measure.map (fun a => ∑ α : Fin m, c α * evalSingle φ W a (X α))
        (gaussianReadoutMeasure n) =
        Measure.map (fun a => ∑ i : Fin n, a i * psi n φ W X c i)
          (gaussianReadoutMeasure n) := by
      congr 1
      funext a
      exact projection_eq_sum_psi φ W a X c
    _ = gaussianReal 0 (Real.toNNReal (∑ i : Fin n, (psi n φ W X c i) ^ 2)) :=
      map_gaussianReadoutMeasure_inner (psi n φ W X c)
    _ = gaussianReal 0 (Real.toNNReal (c ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ c)) := by
      rw [sum_psi_sq_eq_bilin]

/-- Pushforward under inner product with `t` yields a 1D Gaussian with variance
`t.ofLp ⬝ᵥ Φ^{(n)} *ᵥ t.ofLp`. -/
lemma map_readout_inner_evalVector
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (t : EuclideanSpace ℝ (Fin m)) :
    Measure.map (fun a => ⟪t, evalVector φ W a X⟫) (gaussianReadoutMeasure n) =
      gaussianReal 0 (Real.toNNReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ t.ofLp)) := by
  calc
    Measure.map (fun a => ⟪t, evalVector φ W a X⟫) (gaussianReadoutMeasure n) =
        Measure.map (fun a => ∑ α : Fin m, t.ofLp α * evalSingle φ W a (X α))
          (gaussianReadoutMeasure n) := by
      congr 1
      funext a
      exact evalVector_inner φ W X a t
    _ = gaussianReal 0
        (Real.toNNReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ t.ofLp)) :=
      map_readout_projection_eq_gaussianReal φ W X t.ofLp

/-- The characteristic function of `evalVector` under `gaussianReadoutMeasure n`. -/
lemma charFun_readout_evalVector
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (t : EuclideanSpace ℝ (Fin m)) :
    charFun (Measure.map (fun a => evalVector φ W a X) (gaussianReadoutMeasure n)) t =
      Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ t.ofLp) / 2) := by
  set μ := Measure.map (fun a => evalVector φ W a X) (gaussianReadoutMeasure n)
  rw [charFun_apply]
  have h_meas : Measurable (fun a => evalVector φ W a X) := evalVector_measurable φ W X
  rw [integral_map h_meas.aemeasurable (by fun_prop)]
  have h_exp : (fun a => Complex.exp (⟪evalVector φ W a X, t⟫ * Complex.I)) =
      (fun a => Complex.exp (⟪t, evalVector φ W a X⟫ * Complex.I)) := by
    ext a
    congr 1
    rw [real_inner_comm]
  rw [h_exp]
  have h_meas_inner : Measurable (fun a => ⟪t, evalVector φ W a X⟫) :=
    inner_evalVector_measurable φ W X t
  have h_int_map : (∫ a, Complex.exp (⟪t, evalVector φ W a X⟫ * Complex.I) ∂gaussianReadoutMeasure n) =
      ∫ y : ℝ, Complex.exp (y * Complex.I) ∂Measure.map (fun a => ⟪t, evalVector φ W a X⟫) (gaussianReadoutMeasure n) := by
    rw [integral_map h_meas_inner.aemeasurable (by fun_prop)]
  rw [h_int_map]
  rw [map_readout_inner_evalVector φ W X t]
  have h_cf_1 : (∫ y : ℝ, Complex.exp (y * Complex.I) ∂(gaussianReal 0 (Real.toNNReal (t.ofLp ⬝ᵥ empiricalCovariance n φ W X *ᵥ t.ofLp)))) =
      charFun (gaussianReal 0 (Real.toNNReal (t.ofLp ⬝ᵥ empiricalCovariance n φ W X *ᵥ t.ofLp))) 1 := by
    rw [charFun_apply_real]
    simp
  rw [h_cf_1, charFun_gaussianReal]
  simp only [Complex.ofReal_zero, mul_zero, zero_mul, Complex.ofReal_one, mul_one, one_pow, zero_sub]
  have h_nonneg : 0 ≤ t.ofLp ⬝ᵥ empiricalCovariance n φ W X *ᵥ t.ofLp :=
    empiricalCovariance_nonneg n φ W X t.ofLp
  rw [Real.coe_toNNReal _ h_nonneg]
  congr 1
  rw [neg_div]

/-- **Step 5 / Theorem 1 (Exact Conditional Normality)**:
Conditional on the input weights `W` (the sub-$\sigma$-algebra $\mathcal{F}$), the output
vector `f_m(W, a)` under the readout distribution is an exact centered multivariate Gaussian:
  `f_m | ℱ ~ 𝒩(0, Φ^{(n)})`.

Informal proof:
By the Cramér-Wold device (extensionality of characteristic functions in Mathlib),
two finite measures are equal if their Fourier transforms (characteristic functions) coincide.
For every projection vector `t ∈ EuclideanSpace ℝ (Fin m)`, the characteristic function of the
pushforward measure is computed via the 1D projection theorem to be
`exp(- (1/2) t ⬝ᵥ Φ^{(n)} *ᵥ t)`. This matches the characteristic function of Mathlib's
`multivariateGaussian 0 Φ^{(n)}` exactly, proving Theorem 1. -/
theorem exact_conditional_normality
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) :
    Measure.map (fun a => evalVector φ W a X) (gaussianReadoutMeasure n) =
      multivariateGaussian (0 : EuclideanSpace ℝ (Fin m)) (empiricalCovariance n φ W X) := by
  have hPos : (empiricalCovariance n φ W X).PosSemidef :=
    empiricalCovariance_posSemidef n φ W X
  apply Measure.ext_of_charFun
  ext t
  rw [charFun_readout_evalVector]
  rw [charFun_multivariateGaussian hPos]
  congr 1
  simp only [inner_zero_right, Complex.ofReal_zero, zero_mul, zero_sub, neg_div]

/-- The conditional distribution of the output vector satisfies `IsGaussian`. -/
instance isGaussian_conditional_output
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) :
    IsGaussian (Measure.map (fun a => evalVector φ W a X) (gaussianReadoutMeasure n)) := by
  rw [exact_conditional_normality]
  infer_instance

/-- The conditional expectation of the output vector vanishes. -/
lemma integral_conditional_output_eq_zero
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) :
    ∫ v, v ∂(Measure.map (fun a => evalVector φ W a X) (gaussianReadoutMeasure n)) = 0 := by
  rw [exact_conditional_normality]
  exact integral_id_multivariateGaussian

/-- The conditional covariance between outputs `f(X α)` and `f(X β)` is `Φ^{(n), α β}`. -/
lemma cov_conditional_output_eq_covariance
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) (α β : Fin m) :
    cov[fun v => v.ofLp α, fun v => v.ofLp β;
      Measure.map (fun a => evalVector φ W a X) (gaussianReadoutMeasure n)] =
      empiricalCovariance n φ W X α β := by
  rw [exact_conditional_normality]
  have hPos : (empiricalCovariance n φ W X).PosSemidef :=
    empiricalCovariance_posSemidef n φ W X
  have (i : Fin m) : (fun (v : EuclideanSpace ℝ (Fin m)) => v.ofLp i) = (fun v => v i) := rfl
  rw [this, this]
  exact covariance_eval_multivariateGaussian hPos α β

end Theorem1

section Theorem2

/-! ## Theorem 2: Asymptotic Kernel Convergence and the NNGP Limit -/

/-! ### Step 1: Summand Measurability -/

/-- Step 1 (Measurability): For measurable `φ`, the product `w ↦ φ(w ⊙ x) * φ(w ⊙ x')` is measurable. -/
lemma measurable_cov_summand (φ : ℝ → ℝ) (hφ : Measurable φ) (x x' : Fin d → ℝ) :
    Measurable (fun w : Fin d → ℝ => φ (w ⊙ x) * φ (w ⊙ x')) :=
  (hφ.comp (measurable_innerProduct_left x)).mul (hφ.comp (measurable_innerProduct_left x'))

/-! ### Step 3: Integrability via Cauchy-Schwarz -/

/-- Step 3 (Integrability via Cauchy-Schwarz): If `φ(· ⊙ x)` and `φ(· ⊙ x')` are square-integrable
under the Gaussian row measure, their product is integrable. -/
lemma integrable_cov_summand_of_memLp
    (φ : ℝ → ℝ) (x x' : Fin d → ℝ)
    (hx : MemLp (fun w => φ (w ⊙ x)) 2 (gaussianRowMeasure d))
    (hx' : MemLp (fun w => φ (w ⊙ x')) 2 (gaussianRowMeasure d)) :
    Integrable (fun w => φ (w ⊙ x) * φ (w ⊙ x')) (gaussianRowMeasure d) :=
  hx.integrable_mul hx'

/-! ### Step 2 & Step 4: SLLN Convergence (Entrywise and Full Matrix) -/

/-- **Theorem 2 (Entrywise SLLN for the Covariance Tensor)**:
As width `n → ∞`, each entry of the empirical covariance matrix converges almost surely to the
deterministic limiting NNGP expectation:
  `Φ^{(n), α β} →_as 𝔼_{w ~ 𝒩(0, I_d)}[φ(w ⊙ X α) φ(w ⊙ X β)]`.

**Proof (4 Steps)**:
* Step 1: For fixed inputs `X α, X β`, define the summands `Y_i(rows) := φ(rows i ⊙ X α) φ(rows i ⊙ X β)`.
* Step 2: Because `rows` are i.i.d. under the infinite product measure `μ`, `{Y_i}` is i.i.d.
* Step 3: By square-integrability of `φ` and Cauchy-Schwarz (`MemLp.integrable_mul`), `Y_0` is integrable.
* Step 4: By Kolmogorov/Etemadi's SLLN (`strong_law_ae`), `(1/n) ∑_{i=1}^n Y_i →_as 𝔼[Y_0]`. -/
theorem empiricalCovariance_tendsto_integral
    (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ)
    (hφ_meas : Measurable φ)
    (hφ_L2 : ∀ α, MemLp (fun w => φ (w ⊙ X α)) 2 (gaussianRowMeasure d))
    (α β : Fin m) :
    ∀ᵐ rows : ℕ → Fin d → ℝ ∂(Measure.infinitePi fun _ => gaussianRowMeasure d),
      Filter.Tendsto
        (fun n : ℕ => empiricalCovariance n φ (fun i => rows i.val) X α β)
      Filter.atTop
      (nhds (∫ w, φ (w ⊙ X α) * φ (w ⊙ X β) ∂(gaussianRowMeasure d))) := by
  set g := fun w : Fin d → ℝ => φ (w ⊙ X α) * φ (w ⊙ X β)
  have hg_meas : Measurable g := measurable_cov_summand φ hφ_meas (X α) (X β)
  have hg_int : Integrable g (gaussianRowMeasure d) :=
    integrable_cov_summand_of_memLp φ (X α) (X β) (hφ_L2 α) (hφ_L2 β)
  simpa only [empiricalCovariance, g] using
    gaussianRow_average_tendsto_integral g hg_meas hg_int

/-- **Theorem 2 (Full Matrix Strong Law of Large Numbers for the Covariance Tensor)**:
As width `n → ∞`, the empirical covariance matrix converges almost surely to the deterministic
limiting NNGP Gram matrix in `Matrix (Fin m) (Fin m) ℝ`:
  `Φ^{(n)} →_as (fun α β => 𝔼_{w ~ 𝒩(0, I_d)}[φ(w ⊙ X α) φ(w ⊙ X β)])`. -/
theorem empiricalCovariance_tendsto_matrix_integral
    (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ)
    (hφ_meas : Measurable φ)
    (hφ_L2 : ∀ α, MemLp (fun w => φ (w ⊙ X α)) 2 (gaussianRowMeasure d)) :
    ∀ᵐ rows : ℕ → Fin d → ℝ ∂(Measure.infinitePi fun _ => gaussianRowMeasure d),
      Filter.Tendsto
        (fun n : ℕ => empiricalCovariance n φ (fun i => rows i.val) X)
        Filter.atTop
        (nhds ((fun α β => ∫ w, φ (w ⊙ X α) * φ (w ⊙ X β) ∂(gaussianRowMeasure d)) : Matrix (Fin m) (Fin m) ℝ)) := by
  have h_entry : ∀ α β : Fin m,
      ∀ᵐ rows : ℕ → Fin d → ℝ ∂(Measure.infinitePi fun _ => gaussianRowMeasure d),
        Filter.Tendsto
          (fun n : ℕ => empiricalCovariance n φ (fun i => rows i.val) X α β)
          Filter.atTop
          (nhds (∫ w, φ (w ⊙ X α) * φ (w ⊙ X β) ∂(gaussianRowMeasure d))) :=
    fun α β => empiricalCovariance_tendsto_integral φ X hφ_meas hφ_L2 α β
  have h_all :
      ∀ᵐ rows : ℕ → Fin d → ℝ ∂(Measure.infinitePi fun _ => gaussianRowMeasure d),
        ∀ α β : Fin m,
          Filter.Tendsto
            (fun n : ℕ => empiricalCovariance n φ (fun i => rows i.val) X α β)
            Filter.atTop
            (nhds (∫ w, φ (w ⊙ X α) * φ (w ⊙ X β) ∂(gaussianRowMeasure d))) := by
    simp_rw [ae_all_iff]
    exact h_entry
  filter_upwards [h_all] with rows hrows
  refine tendsto_pi_nhds.2 fun α => tendsto_pi_nhds.2 fun β => ?_
  exact hrows α β

end Theorem2

section Theorem3

/-! ## Theorem 3: Asymptotic Convergence in Distribution to NNGP -/

/-! ### Limiting NNGP Covariance Matrix and Output Distribution -/

/-- The limiting NNGP covariance matrix `Φ^{(∞)} ∈ ℝ^{m × m}`:
  `Φ^{(∞), α β} = ∫ w, φ (w ⊙ X α) * φ (w ⊙ X β) ∂(gaussianRowMeasure d)`. -/
noncomputable def limitingCovariance
    (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ) : Matrix (Fin m) (Fin m) ℝ :=
  fun α β => ∫ w, φ (w ⊙ X α) * φ (w ⊙ X β) ∂(gaussianRowMeasure d)

/-- Equation lemma for `limitingCovariance`. -/
lemma limitingCovariance_apply
    (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ) (α β : Fin m) :
    limitingCovariance φ X α β =
      ∫ w, φ (w ⊙ X α) * φ (w ⊙ X β) ∂(gaussianRowMeasure d) := rfl

/-- The limiting NNGP covariance matrix is symmetric (Hermitian). -/
lemma limitingCovariance_isHermitian
    (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ) :
    (limitingCovariance φ X).IsHermitian := by
  ext α β
  simp only [limitingCovariance_apply, conjTranspose_apply, star_trivial]
  congr 1 with w
  ring

/-- Full matrix almost sure convergence from Theorem 2 packaged with `limitingCovariance`. -/
lemma empiricalCovariance_tendsto_limitingCovariance
    (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ)
    (hφ_meas : Measurable φ)
    (hφ_L2 : ∀ α, MemLp (fun w => φ (w ⊙ X α)) 2 (gaussianRowMeasure d)) :
    ∀ᵐ rows : ℕ → Fin d → ℝ ∂(Measure.infinitePi fun _ => gaussianRowMeasure d),
      Filter.Tendsto
        (fun n : ℕ => empiricalCovariance n φ (fun i => rows i.val) X)
        Filter.atTop
        (nhds (limitingCovariance φ X)) :=
  empiricalCovariance_tendsto_matrix_integral φ X hφ_meas hφ_L2

/-- The quadratic form with a matrix `M ↦ c ⬝ᵥ M *ᵥ c` is continuous. -/
lemma continuous_matrix_quadratic (c : Fin m → ℝ) :
    Continuous (fun M : Matrix (Fin m) (Fin m) ℝ => c ⬝ᵥ M *ᵥ c) := by
  have h_eq : (fun M : Matrix (Fin m) (Fin m) ℝ => c ⬝ᵥ M *ᵥ c) =
      fun M => ∑ α : Fin m, ∑ β : Fin m, c α * M α β * c β := by
    funext M
    rw [Matrix.dot_mulVec_eq_sum_sum, Finset.sum_comm]
  rw [h_eq]
  have h_entry (α β : Fin m) : Continuous (fun M : Matrix (Fin m) (Fin m) ℝ => M α β) :=
    (continuous_apply β).comp (continuous_apply α)
  refine continuous_finsetSum _ fun α _ => continuous_finsetSum _ fun β _ => ?_
  exact (continuous_const.mul (h_entry α β)).mul continuous_const

/-- The quadratic form with the limiting NNGP covariance matrix `c ⬝ᵥ Φ^{(∞)} *ᵥ c` is nonnegative. -/
lemma limitingCovariance_nonneg
    (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ)
    (hφ_meas : Measurable φ)
    (hφ_L2 : ∀ α, MemLp (fun w => φ (w ⊙ X α)) 2 (gaussianRowMeasure d))
    (c : Fin m → ℝ) :
    0 ≤ c ⬝ᵥ (limitingCovariance φ X) *ᵥ c := by
  have h_ae := empiricalCovariance_tendsto_limitingCovariance φ X hφ_meas hφ_L2
  obtain ⟨rows, hrows⟩ := h_ae.exists
  have h_tend : Filter.Tendsto
      (fun n : ℕ => c ⬝ᵥ (empiricalCovariance n φ (fun i => rows i.val) X) *ᵥ c)
      Filter.atTop
      (nhds (c ⬝ᵥ (limitingCovariance φ X) *ᵥ c)) :=
    ((continuous_matrix_quadratic c).tendsto (limitingCovariance φ X)).comp hrows
  refine ge_of_tendsto h_tend ?_
  filter_upwards with n
  exact empiricalCovariance_nonneg n φ (fun i => rows i.val) X c

/-- The limiting NNGP covariance matrix `Φ^{(∞)}` is positive semidefinite (`PosSemidef`). -/
theorem limitingCovariance_posSemidef
    (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ)
    (hφ_meas : Measurable φ)
    (hφ_L2 : ∀ α, MemLp (fun w => φ (w ⊙ X α)) 2 (gaussianRowMeasure d)) :
    (limitingCovariance φ X).PosSemidef :=
  posSemidef_of_bilin_nonneg _ (limitingCovariance_isHermitian φ X)
    (limitingCovariance_nonneg φ X hφ_meas hφ_L2)

lemma evalSingle_joint_measurable
    (φ : ℝ → ℝ) (hφ : Measurable φ) (x : Fin d → ℝ) :
    Measurable (fun p : (Fin n → Fin d → ℝ) × (Fin n → ℝ) => evalSingle φ p.1 p.2 x) := by
  simp_rw [evalSingle_eq_normalized_sum]
  refine Measurable.const_mul ?_ _
  refine Finset.measurable_sum _ fun i _ => ?_
  have h_ai : Measurable (fun p : (Fin n → Fin d → ℝ) × (Fin n → ℝ) => p.2 i) :=
    (measurable_pi_apply i).comp measurable_snd
  have h_Wi : Measurable (fun p : (Fin n → Fin d → ℝ) × (Fin n → ℝ) => φ (p.1 i ⊙ x)) := by
    refine hφ.comp ?_
    exact (measurable_innerProduct_left x).comp ((measurable_pi_apply i).comp measurable_fst)
  exact h_ai.mul h_Wi

lemma evalVector_joint_measurable
    (φ : ℝ → ℝ) (hφ : Measurable φ) (X : Fin m → Fin d → ℝ) :
    Measurable (fun p : (Fin n → Fin d → ℝ) × (Fin n → ℝ) => evalVector φ p.1 p.2 X) := by
  change Measurable ((WithLp.toLp 2) ∘
    (fun (p : (Fin n → Fin d → ℝ) × (Fin n → ℝ)) α => evalSingle φ p.1 p.2 (X α)))
  refine (PiLp.continuous_toLp 2 _).measurable.comp ?_
  exact measurable_pi_iff.2 fun α => evalSingle_joint_measurable φ hφ (X α)

/-- Joint distribution of network outputs across evaluation points `X` at width `n`:
  `outputMeasure n d φ X = (initMeasure n d).map (fun (W, a) => evalVector φ W a X)`. -/
noncomputable def outputMeasure (n d : ℕ) (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ) :
    Measure (EuclideanSpace ℝ (Fin m)) :=
  Measure.map (fun p => evalVector φ p.1 p.2 X) (initMeasure n d)

/-- The output law as the pushforward of the joint initialization measure. This is the public
equation lemma for `outputMeasure`, so downstream proofs need not unfold its implementation. -/
lemma outputMeasure_eq_map
    (n d : ℕ) (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ) :
    outputMeasure n d φ X =
      Measure.map (fun p => evalVector φ p.1 p.2 X) (initMeasure n d) := rfl

/-- `outputMeasure n d φ X` is a probability measure when `φ` is measurable. -/
lemma isProbabilityMeasure_outputMeasure
    (n d : ℕ) (φ : ℝ → ℝ) (hφ : Measurable φ) (X : Fin m → Fin d → ℝ) :
    IsProbabilityMeasure (outputMeasure n d φ X) := by
  rw [outputMeasure_eq_map]
  exact Measure.isProbabilityMeasure_map (evalVector_joint_measurable φ hφ X).aemeasurable

/-- Transport: The pushforward of the infinite Gaussian row product measure under restriction to the
first `n` hidden units is exactly the finite-width input weight measure `gaussianInit n d`. -/
lemma map_infinitePi_rows_eq_gaussianInit (n d : ℕ) :
    Measure.map (fun (rows : ℕ → Fin d → ℝ) (i : Fin n) => rows i.val)
      (Measure.infinitePi fun _ : ℕ => gaussianRowMeasure d) = gaussianInit n d := by
  rw [Measure.map_infinitePi_infinitePi_of_inj Fin.val_injective]
  rw [Measure.infinitePi_eq_pi]
  rfl

/-! ### Step 1 & Step 2: Unconditional Characteristic Function -/

/-- Step 1 & 2 helper: Integrating out the readout weights under `gaussianReadoutMeasure n` gives the
conditional characteristic function `exp(- (1/2) t ⬝ᵥ Φ^{(n)} *ᵥ t)`. -/
lemma integral_exp_inner_evalVector
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (t : EuclideanSpace ℝ (Fin m)) :
    (∫ a, Complex.exp (⟪evalVector φ W a X, t⟫ * Complex.I) ∂(gaussianReadoutMeasure n)) =
      Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ t.ofLp) / 2) := by
  have h_meas : Measurable (fun a => evalVector φ W a X) := evalVector_measurable φ W X
  calc
    (∫ a, Complex.exp (⟪evalVector φ W a X, t⟫ * Complex.I)
        ∂(gaussianReadoutMeasure n)) =
        charFun (Measure.map (fun a => evalVector φ W a X) (gaussianReadoutMeasure n)) t := by
      rw [charFun_apply, integral_map h_meas.aemeasurable (by fun_prop)]
    _ = Complex.exp
        (- Complex.ofReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ t.ofLp) / 2) :=
      charFun_readout_evalVector φ W X t

/-- **Step 2 (Law of Total Expectation for the Characteristic Function)**:
The unconditional characteristic function of the network output vector under `initMeasure n d` is the
expectation over input weights `W` of the conditional characteristic function:
  `charFun (outputMeasure n d φ X) t = 𝔼_W [exp(- (1/2) t ⬝ᵥ Φ^{(n)}(W) *ᵥ t)]`. -/
lemma charFun_outputMeasure
    (n : ℕ) (φ : ℝ → ℝ) (hφ : Measurable φ) (X : Fin m → Fin d → ℝ)
    (t : EuclideanSpace ℝ (Fin m)) :
    charFun (outputMeasure n d φ X) t =
      ∫ W, Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ t.ofLp) / 2)
        ∂(gaussianInit n d) := by
  have h_meas : Measurable (fun p : (Fin n → Fin d → ℝ) × (Fin n → ℝ) => evalVector φ p.1 p.2 X) :=
    evalVector_joint_measurable φ hφ X
  calc
    charFun (outputMeasure n d φ X) t =
        ∫ p, Complex.exp (⟪evalVector φ p.1 p.2 X, t⟫ * Complex.I) ∂(initMeasure n d) := by
      rw [outputMeasure_eq_map, charFun_apply,
        integral_map h_meas.aemeasurable (by fun_prop)]
    _ = ∫ W, (∫ a, Complex.exp (⟪evalVector φ W a X, t⟫ * Complex.I)
          ∂(gaussianReadoutMeasure n)) ∂(gaussianInit n d) := by
      change (∫ p, Complex.exp (⟪evalVector φ p.1 p.2 X, t⟫ * Complex.I)
          ∂((gaussianInit n d).prod (gaussianReadoutMeasure n))) = _
      have h_inner : Measurable
          (fun p : (Fin n → Fin d → ℝ) × (Fin n → ℝ) =>
            ⟪evalVector φ p.1 p.2 X, t⟫) :=
        (continuous_id.inner continuous_const).measurable.comp h_meas
      have h_exp_meas : AEStronglyMeasurable
          (fun p : (Fin n → Fin d → ℝ) × (Fin n → ℝ) =>
            Complex.exp (⟪evalVector φ p.1 p.2 X, t⟫ * Complex.I))
          ((gaussianInit n d).prod (gaussianReadoutMeasure n)) :=
        (Complex.continuous_exp.measurable.comp
          ((Complex.measurable_ofReal.comp h_inner).mul_const Complex.I)).aestronglyMeasurable
      exact integral_prod _ (Integrable.of_bound h_exp_meas 1
        (ae_of_all _ fun p => (Complex.norm_exp_ofReal_mul_I _).le))
    _ = ∫ W, Complex.exp
        (- Complex.ofReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ t.ofLp) / 2)
          ∂(gaussianInit n d) := by
      congr 1 with W
      exact integral_exp_inner_evalVector φ W X t

/-- Measurability of the characteristic integrand on input weight matrices. -/
lemma measurable_exp_quadratic_empiricalCovariance
    (n : ℕ) (φ : ℝ → ℝ) (hφ : Measurable φ) (X : Fin m → Fin d → ℝ)
    (t : EuclideanSpace ℝ (Fin m)) :
    Measurable (fun W : Fin n → Fin d → ℝ =>
      Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ t.ofLp) / 2)) := by
  have h_quad : Measurable (fun W : Fin n → Fin d → ℝ =>
      t.ofLp ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ t.ofLp) := by
    have h_eq : (fun W : Fin n → Fin d → ℝ => t.ofLp ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ t.ofLp) =
        fun W => ∑ α : Fin m, ∑ β : Fin m, t.ofLp α * (empiricalCovariance n φ W X α β) * t.ofLp β := by
      funext W
      rw [Matrix.dot_mulVec_eq_sum_sum, Finset.sum_comm]
    rw [h_eq]
    refine Finset.measurable_sum _ fun α _ => Finset.measurable_sum _ fun β _ => ?_
    have h_cov : Measurable (fun W : Fin n → Fin d → ℝ => empiricalCovariance n φ W X α β) := by
      simp only [empiricalCovariance]
      refine Measurable.const_mul ?_ _
      refine Finset.measurable_sum _ fun i _ => ?_
      have h_summand : Measurable (fun w : Fin d → ℝ => φ (w ⊙ X α) * φ (w ⊙ X β)) :=
        measurable_cov_summand φ hφ (X α) (X β)
      exact h_summand.comp (measurable_pi_apply i)
    exact (measurable_const.mul h_cov).mul measurable_const
  refine Complex.measurable_exp.comp ?_
  refine Measurable.div_const ?_ 2
  refine Measurable.neg ?_
  exact Complex.measurable_ofReal.comp h_quad

/-- The characteristic integrand `M ↦ exp(- (1/2) t ⬝ᵥ M *ᵥ t)` is continuous. -/
lemma continuous_charFun_integrand (t : EuclideanSpace ℝ (Fin m)) :
    Continuous (fun M : Matrix (Fin m) (Fin m) ℝ =>
      Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ M *ᵥ t.ofLp) / 2)) := by
  refine Complex.continuous_exp.comp ?_
  refine Continuous.div_const ?_ 2
  refine Continuous.neg ?_
  refine Complex.continuous_ofReal.comp ?_
  exact continuous_matrix_quadratic t.ofLp

/-- Expressing the expectation under `gaussianInit n d` as an expectation under `infinitePi`. -/
lemma integral_charFun_gaussianInit_eq_infinitePi
    (n : ℕ) (φ : ℝ → ℝ) (hφ : Measurable φ) (X : Fin m → Fin d → ℝ)
    (t : EuclideanSpace ℝ (Fin m)) :
    (∫ W, Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ t.ofLp) / 2)
      ∂(gaussianInit n d)) =
    ∫ rows, Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ (fun i => rows i.val) X) *ᵥ t.ofLp) / 2)
      ∂(Measure.infinitePi fun _ : ℕ => gaussianRowMeasure d) := by
  rw [← map_infinitePi_rows_eq_gaussianInit n d]
  have h_map : Measurable (fun (rows : ℕ → Fin d → ℝ) (i : Fin n) => rows i.val) :=
    measurable_pi_iff.2 fun i => measurable_pi_apply i.val
  have h_f : Measurable (fun W : Fin n → Fin d → ℝ =>
      Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ t.ofLp) / 2)) :=
    measurable_exp_quadratic_empiricalCovariance n φ hφ X t
  rw [integral_map h_map.aemeasurable h_f.aestronglyMeasurable]

/-! ### Step 3 & Step 4: Dominated Convergence of the Characteristic Function -/

/-- **Step 3 (Almost sure convergence of characteristic integrand)**:
By Theorem 2, `Φ^{(n)} →_as Φ^{(∞)}`. By continuity of `M ↦ exp(- (1/2) t ⬝ᵥ M *ᵥ t)`, the
characteristic integrand converges almost surely. -/
lemma charFun_integrand_tendsto_ae
    (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ)
    (hφ_meas : Measurable φ)
    (hφ_L2 : ∀ α, MemLp (fun w => φ (w ⊙ X α)) 2 (gaussianRowMeasure d))
    (t : EuclideanSpace ℝ (Fin m)) :
    ∀ᵐ rows : ℕ → Fin d → ℝ ∂(Measure.infinitePi fun _ => gaussianRowMeasure d),
      Filter.Tendsto
        (fun n : ℕ => Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ (fun i => rows i.val) X) *ᵥ t.ofLp) / 2))
        Filter.atTop
        (nhds (Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (limitingCovariance φ X) *ᵥ t.ofLp) / 2))) := by
  have h_mat := empiricalCovariance_tendsto_limitingCovariance φ X hφ_meas hφ_L2
  filter_upwards [h_mat] with rows hrows
  exact ((continuous_charFun_integrand t).tendsto (limitingCovariance φ X)).comp hrows

/-- Auxiliary: `‖exp(- s / 2)‖ ≤ 1` for nonnegative real `s`. -/
lemma norm_exp_neg_ofReal_div_two_le_one {s : ℝ} (hs : 0 ≤ s) :
    ‖Complex.exp (- Complex.ofReal s / 2)‖ ≤ 1 := by
  have h_re : (- Complex.ofReal s / 2).re = - s / 2 := by simp
  rw [Complex.norm_exp, h_re]
  have h_le : - s / 2 ≤ 0 := by linarith
  have h_exp := Real.exp_le_exp_of_le h_le
  rwa [Real.exp_zero] at h_exp

/-- Step 4 uniform bound: The characteristic integrand is bounded by `1` uniformly in `n` and `W`. -/
lemma norm_charFun_readout_le_one
    (n : ℕ) (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (t : EuclideanSpace ℝ (Fin m)) :
    ‖Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ t.ofLp) / 2)‖ ≤ 1 :=
  norm_exp_neg_ofReal_div_two_le_one (empiricalCovariance_nonneg n φ W X t.ofLp)

/-- Step 4 (DCT under infinite product): The infinite-product integral of the characteristic integrand
converges to `exp(- (1/2) t ⬝ᵥ Φ^{(∞)} *ᵥ t)`. -/
lemma tendsto_integral_charFun_infinitePi
    (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ)
    (hφ_meas : Measurable φ)
    (hφ_L2 : ∀ α, MemLp (fun w => φ (w ⊙ X α)) 2 (gaussianRowMeasure d))
    (t : EuclideanSpace ℝ (Fin m)) :
    Filter.Tendsto
      (fun n : ℕ =>
        ∫ rows, Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ (fun i => rows i.val) X) *ᵥ t.ofLp) / 2)
          ∂(Measure.infinitePi fun _ : ℕ => gaussianRowMeasure d))
      Filter.atTop
      (nhds (Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (limitingCovariance φ X) *ᵥ t.ofLp) / 2))) := by
  have h_ae := charFun_integrand_tendsto_ae φ X hφ_meas hφ_L2 t
  have h_bound : ∀ n : ℕ, ∀ᵐ rows : ℕ → Fin d → ℝ ∂(Measure.infinitePi fun _ : ℕ => gaussianRowMeasure d),
      ‖Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ (fun i => rows i.val) X) *ᵥ t.ofLp) / 2)‖ ≤ (1 : ℝ) :=
    fun n => ae_of_all _ fun rows => norm_charFun_readout_le_one n φ _ X t
  have h_meas (n : ℕ) : Measurable (fun rows : ℕ → Fin d → ℝ =>
      Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ (fun i => rows i.val) X) *ᵥ t.ofLp) / 2)) := by
    have h_map : Measurable (fun (rows : ℕ → Fin d → ℝ) (i : Fin n) => rows i.val) :=
      measurable_pi_iff.2 fun i => measurable_pi_apply i.val
    exact (measurable_exp_quadratic_empiricalCovariance n φ hφ_meas X t).comp h_map
  have h_lim := tendsto_integral_of_dominated_convergence (bound := fun _ => (1 : ℝ))
    (fun n => (h_meas n).aestronglyMeasurable)
    (integrable_const 1)
    h_bound
    h_ae
  simpa only [integral_const, probReal_univ, one_smul] using h_lim

/-- **Step 4 (Dominated Convergence Theorem for Characteristic Functions)**:
The unconditional characteristic function of the network output converges to the Gaussian characteristic
function:
  `lim_{n → ∞} charFun (outputMeasure n d φ X) t = exp(- (1/2) t ⬝ᵥ Φ^{(∞)} *ᵥ t)`. -/
lemma tendsto_charFun_outputMeasure
    (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ)
    (hφ_meas : Measurable φ)
    (hφ_L2 : ∀ α, MemLp (fun w => φ (w ⊙ X α)) 2 (gaussianRowMeasure d))
    (t : EuclideanSpace ℝ (Fin m)) :
    Filter.Tendsto
      (fun n : ℕ => charFun (outputMeasure n d φ X) t)
      Filter.atTop
      (nhds (Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (limitingCovariance φ X) *ᵥ t.ofLp) / 2))) := by
  have h_eq (n : ℕ) : charFun (outputMeasure n d φ X) t =
      ∫ rows, Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ (fun i => rows i.val) X) *ᵥ t.ofLp) / 2)
        ∂(Measure.infinitePi fun _ : ℕ => gaussianRowMeasure d) := by
    rw [charFun_outputMeasure n φ hφ_meas X t,
      integral_charFun_gaussianInit_eq_infinitePi n φ hφ_meas X t]
  simp_rw [h_eq]
  exact tendsto_integral_charFun_infinitePi φ X hφ_meas hφ_L2 t

/-! ### Step 5: Lévy Continuity Theorem and Theorem 3 Statements -/

/-- Pointwise convergence of characteristic functions to the characteristic function of the
multivariate Gaussian `𝒩(0, Φ^{(∞)})`. -/
lemma tendsto_charFun_outputMeasure_eq_multivariateGaussian
    (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ)
    (hφ_meas : Measurable φ)
    (hφ_L2 : ∀ α, MemLp (fun w => φ (w ⊙ X α)) 2 (gaussianRowMeasure d))
    (t : EuclideanSpace ℝ (Fin m)) :
    Filter.Tendsto
      (fun n : ℕ => charFun (outputMeasure n d φ X) t)
      Filter.atTop
      (nhds (charFun (multivariateGaussian (0 : EuclideanSpace ℝ (Fin m)) (limitingCovariance φ X)) t)) := by
  have hPos : (limitingCovariance φ X).PosSemidef :=
    limitingCovariance_posSemidef φ X hφ_meas hφ_L2
  have h_cf : charFun (multivariateGaussian (0 : EuclideanSpace ℝ (Fin m)) (limitingCovariance φ X)) t =
      Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (limitingCovariance φ X) *ᵥ t.ofLp) / 2) := by
    rw [charFun_multivariateGaussian hPos]
    congr 1
    simp only [inner_zero_right, Complex.ofReal_zero, zero_mul, zero_sub, neg_div]
  rw [h_cf]
  exact tendsto_charFun_outputMeasure φ X hφ_meas hφ_L2 t

/-- **Theorem 3 (Weak Convergence of Output Measure to NNGP Limit)**:
As width `n → ∞`, the joint distribution of network outputs across evaluation points
converges weakly to the multivariate Gaussian distribution `𝒩(0, Φ^{(∞)})`:
  `outputMeasure n d φ X →_w 𝒩(0, Φ^{(∞)})`. -/
theorem outputMeasure_tendsto_multivariateGaussian
    (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ)
    (hφ_meas : Measurable φ)
    (hφ_L2 : ∀ α, MemLp (fun w => φ (w ⊙ X α)) 2 (gaussianRowMeasure d)) :
    Filter.Tendsto (β := ProbabilityMeasure (EuclideanSpace ℝ (Fin m)))
      (fun n : ℕ => ⟨outputMeasure n d φ X,
        isProbabilityMeasure_outputMeasure n d φ hφ_meas X⟩)
      Filter.atTop
      (nhds ⟨multivariateGaussian 0 (limitingCovariance φ X), inferInstance⟩) := by
  apply ProbabilityMeasure.tendsto_of_tendsto_charFun
  intro t
  exact tendsto_charFun_outputMeasure_eq_multivariateGaussian φ X hφ_meas hφ_L2 t

set_option backward.isDefEq.respectTransparency.types false in
/-- **Theorem 3 (Asymptotic Convergence in Distribution to NNGP)**:
As width `n → ∞`, the output vector `f_m(W, a)` under the parameter initialization
measure converges in distribution to the centered multivariate Gaussian `𝒩(0, Φ^{(∞)})`:
  `(f(x^1; θ), …, f(x^m; θ))ᵀ →_d 𝒩(0, Φ^{(∞)})`.

**Proof (5 Steps)**:
* Step 1: By `charFun_readout_evalVector`, the conditional characteristic function given input weights
  `W` (the σ-algebra `ℱ`) is `exp(- (1/2) t ⬝ᵥ Φ^{(n)} *ᵥ t)`.
* Step 2: By Fubini (`charFun_outputMeasure`), the unconditional characteristic function is the
  expectation `𝔼_W [exp(- (1/2) t ⬝ᵥ Φ^{(n)} *ᵥ t)]`.
* Step 3: By Theorem 2 (`empiricalCovariance_tendsto_limitingCovariance`), `Φ^{(n)} →_as Φ^{(∞)}`,
  so the characteristic integrand converges almost surely (`charFun_integrand_tendsto_ae`).
* Step 4: Since `Φ^{(n)}` is positive semidefinite, `‖exp(- (1/2) t ⬝ᵥ Φ^{(n)} *ᵥ t)‖ ≤ 1`.
  By the Dominated Convergence Theorem (`tendsto_charFun_outputMeasure`),
  `charFun (outputMeasure n) t → exp(- (1/2) t ⬝ᵥ Φ^{(∞)} *ᵥ t)`.
* Step 5: By Lévy's Continuity Theorem (`ProbabilityMeasure.tendsto_of_tendsto_charFun`), pointwise
  characteristic function convergence implies weak convergence and convergence in distribution. -/
theorem tendstoInDistribution_evalVector
    (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ)
    (hφ_meas : Measurable φ)
    (hφ_L2 : ∀ α, MemLp (fun w => φ (w ⊙ X α)) 2 (gaussianRowMeasure d)) :
    TendstoInDistribution
      (fun n (p : (Fin n → Fin d → ℝ) × (Fin n → ℝ)) => evalVector φ p.1 p.2 X)
      Filter.atTop
      id
      (fun n => initMeasure n d)
      (multivariateGaussian 0 (limitingCovariance φ X)) where
  forall_aemeasurable n := (evalVector_joint_measurable φ hφ_meas X).aemeasurable
  aemeasurable_limit := measurable_id.aemeasurable
  tendsto := by
    convert! outputMeasure_tendsto_multivariateGaussian φ X hφ_meas hφ_L2
    exact Subtype.ext Measure.map_id

end Theorem3

end NTK

end
