/-
Copyright (c) 2026 LML Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: LML Contributors
-/
module

public import LeanMachineLearning.Optimization.NTK.Basic
public import LeanMachineLearning.Optimization.NTK.Kernel
public import Mathlib.Probability.Distributions.Gaussian.Multivariate
public import Mathlib.Probability.Distributions.Gaussian.Real
public import Mathlib.Probability.Distributions.Gaussian.Basic
public import Mathlib.Probability.Distributions.Gaussian.CharFun
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.Probability.ProductMeasure
public import Mathlib.Probability.StrongLaw
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.LinearAlgebra.Matrix.PosDef

/-!
# NTK Initialization and Exact Finite-Width Conditional Distribution

This file formalizes the parameter initialization probability space, mutual independence
structure, Theorem 1 (Exact Conditional Normality), and Theorem 2 (Strong Law of Large Numbers
for the Covariance Tensor / Asymptotic NNGP Limit) for neural networks.

## Mathematical Formulation

* **Initialization Probability Space and Independence Structure**:
  * Underlying parameter space `(Fin n → Fin d → ℝ) × (Fin n → ℝ)` with product
    measure `initMeasure n d = (gaussianInit n d).prod (gaussianReadoutMeasure n)`.
  * Readout weights: $a_i \stackrel{\text{i.i.d.}}{\sim} \mathcal{N}(0, 1) \quad \forall i$.
  * Input weights:
    $\mathbf{w}_i \stackrel{\text{i.i.d.}}{\sim} \mathcal{N}(\mathbf{0}, \mathbf{I}_{n_0})$.
  * Mutual Independence: $\{a_i\}_{i=1}^n$ is mutually independent of $\{\mathbf{w}_i\}_{i=1}^n$,
    and pairs $(a_i, \mathbf{w}_i)$ are independent across hidden unit indices.

* **Theorem 1 (Exact Conditional Normality)**:
  * Conditional on the sub-$\sigma$-algebra $\mathcal{F}$ generated by input weights $\mathbf{W}$,
    the output vector
    $\mathbf{f}_m := (f(\mathbf{x}^1; \boldsymbol{\theta}), \dots,
      f(\mathbf{x}^m; \boldsymbol{\theta}))^\top$
    is an exact centered multivariate Gaussian vector:
    $$\mathbf{f}_m \mid \mathcal{F} \sim \mathcal{N}\left(\mathbf{0},
      \boldsymbol{\Phi}^{(n)}\right)$$
    where the empirical covariance matrix entries are:
    $$\Phi^{(n), \alpha \beta} := \frac{1}{n} \sum_{i=1}^n \varphi(h_i(\mathbf{x}^\alpha))
      \varphi(h_i(\mathbf{x}^\beta)).$$

* **Proof Steps for Theorem 1**:
  * Step 1: For any projection vector $\mathbf{c} \in \mathbb{R}^m$, the scalar projection is
    $$\sum_{\alpha=1}^m c_\alpha f(\mathbf{x}^\alpha; \boldsymbol{\theta}) =
      \sum_{i=1}^n a_i \psi_i$$
    where $\psi_i := \frac{1}{\sqrt{n}} \sum_{\alpha=1}^m c_\alpha \varphi(h_i(\mathbf{x}^\alpha))$.
  * Step 2: $\psi_i$ is $\mathcal{F}$-measurable, so conditional on $\mathcal{F}$ the coefficients
    $\psi_i$ are deterministic constants.
  * Step 3: $\{a_i\}_{i=1}^n$ are independent of $\mathcal{F}$ and i.i.d. standard Gaussian; thus
    $\sum_{i=1}^n a_i \psi_i$ is a linear combination of independent zero-mean Gaussians.
  * Step 4: The variance of the linear combination is
    $$\sum_{i=1}^n \psi_i^2 = \mathbf{c}^\top \boldsymbol{\Phi}^{(n)} \mathbf{c}.$$
  * Step 5: By Cramér-Wold / linear functional characterization of Gaussianity, every 1D projection
    is $\mathcal{N}(0, \mathbf{c}^\top \boldsymbol{\Phi}^{(n)} \mathbf{c})$, so the conditional
    joint distribution is $\mathcal{N}(\mathbf{0}, \boldsymbol{\Phi}^{(n)})$.

* **Theorem 2 (Strong Law of Large Numbers for the Covariance Tensor / Asymptotic NNGP Limit)**:
  * As width $n \to \infty$, the empirical covariance matrix converges almost surely to the
    deterministic NNGP Gram matrix:
    $$\Phi^{(n), \alpha \beta} \xrightarrow{\text{a.s.}}
      \int \varphi(\mathbf{w} \odot \mathbf{x}^\alpha) \varphi(\mathbf{w} \odot \mathbf{x}^\beta)
      d\mathcal{N}(\mathbf{0}, \mathbf{I})$$
  * Full matrix convergence:
    $\boldsymbol{\Phi}^{(n)} \xrightarrow{\text{a.s.}} \boldsymbol{\Phi}$
    in $\mathbb{R}^{m \times m}$.

* **Proof Steps for Theorem 2**:
  * Step 1: For fixed inputs $\mathbf{x}^\alpha, \mathbf{x}^\beta$,
    define the scalar random variables
    $Y_i := \varphi(h_i(\mathbf{x}^\alpha)) \varphi(h_i(\mathbf{x}^\beta))$ for
    $i \in \{1, \dots, n\}$.
  * Step 2: Because $\{\mathbf{w}_i\}_{i=1}^n$ are i.i.d., the sequence $\{Y_i\}_{i=1}^n$
    is independent and identically distributed.
  * Step 3: By square-integrability of $\varphi$ and Cauchy-Schwarz,
    the expectation exists and is finite:
    $$\mathbb{E}_{\mathbf{w}_i}\left[ |Y_i| \right] \le
      \sqrt{\mathbb{E}_{\mathbf{w}_i}[\varphi(h_i(\mathbf{x}^\alpha))^2]
      \mathbb{E}_{\mathbf{w}_i}[\varphi(h_i(\mathbf{x}^\beta))^2]} < \infty$$
  * Step 4: By Kolmogorov's Strong Law of Large Numbers (SLLN):
    $$\Phi^{(n), \alpha \beta} = \frac{1}{n} \sum_{i=1}^n Y_i
      \xrightarrow{\text{a.s.}} \mathbb{E}_{\mathbf{w}}[Y_1]$$

## Main definitions and theorems

* `NTK.gaussianReadoutMeasure` : transparent product measure $\bigotimes_{i=1}^n \mathcal{N}(0, 1)$.
* `NTK.initMeasure` : joint initialization product measure on parameters.
* `NTK.evalSingle` : scalar network output $f(\mathbf{x}; \mathbf{W}, a)$.
* `NTK.evalVector` : output vector $\mathbf{f}_m(\mathbf{W}, a)$.
* `NTK.empiricalCovariance` : empirical covariance matrix $\boldsymbol{\Phi}^{(n)}$.
* `NTK.psi` : projection coefficients $\psi_i$.
* `NTK.projection_eq_sum_psi` : Step 1 algebraic identity.
* `NTK.sum_psi_sq_eq_bilin` : Step 4 variance identity
  $\sum_i \psi_i^2 = \mathbf{c}^\top \boldsymbol{\Phi}^{(n)} \mathbf{c}$.
* `NTK.empiricalCovariance_posSemidef` : positive semidefiniteness of $\boldsymbol{\Phi}^{(n)}$.
* `NTK.map_readout_projection_eq_gaussianReal` : Step 4 1D conditional normality.
* `NTK.exact_conditional_normality` : Theorem 1 (multivariate conditional normality).
* `NTK.empiricalCovariance_tendsto_integral` : Theorem 2 entrywise almost sure convergence.
* `NTK.empiricalCovariance_tendsto_matrix_integral` : Theorem 2 matrix almost sure convergence.
-/

@[expose] public section

set_option linter.style.longLine false

open Real MeasureTheory ProbabilityTheory Matrix Complex
open scoped BigOperators MatrixOrder RealInnerProductSpace

namespace NTK

variable {d n m : ℕ}

section Preliminaries

/-! ## Network Setup and Initialization Probability Space -/

/-! ### Network Evaluation and Empirical Covariance -/

/-- Single-output evaluation of a two-layer neural network with width `n`, activation `φ`,
input weights `W`, and readout weights `a`:
  `f(x; W, a) = (1/√n) ∑ i, a i * φ (W i ⊙ x)`. -/
noncomputable def evalSingle
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (a : Fin n → ℝ) (x : Fin d → ℝ) : ℝ :=
  (n : ℝ)⁻¹.sqrt * ∑ i : Fin n, a i * φ (W i ⊙ x)

/-- The output vector `f_m(W, a) ∈ ℝᵐ` evaluated at `m` input points `X 0, …, X (m - 1)`:
  `f_m(W, a)_α = f(X α; W, a)`. -/
noncomputable def evalVector
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (a : Fin n → ℝ) (X : Fin m → Fin d → ℝ) :
    EuclideanSpace ℝ (Fin m) :=
  WithLp.toLp 2 (fun α => evalSingle φ W a (X α))

/-- The empirical covariance matrix `Φ^{(n)} ∈ ℝ^{m × m}`:
  `Φ^{(n), α β} = (1/n) ∑ i, φ (W i ⊙ X α) * φ (W i ⊙ X β)`. -/
noncomputable def empiricalCovariance
    (n : ℕ) (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) :
    Matrix (Fin m) (Fin m) ℝ :=
  fun α β => (n : ℝ)⁻¹ * ∑ i : Fin n, φ (W i ⊙ X α) * φ (W i ⊙ X β)

/-! ### API for Network Evaluation -/

@[simp] lemma evalVector_ofLp
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (a : Fin n → ℝ) (X : Fin m → Fin d → ℝ) (α : Fin m) :
    (evalVector φ W a X).ofLp α = evalSingle φ W a (X α) := rfl

lemma evalVector_inner
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (a : Fin n → ℝ) (t : EuclideanSpace ℝ (Fin m)) :
    ⟪t, evalVector φ W a X⟫ = ∑ α : Fin m, t.ofLp α * evalSingle φ W a (X α) := by
  simp only [evalVector, PiLp.inner_apply, RCLike.inner_apply', conj_trivial]

lemma evalVector_continuous
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) :
    Continuous (fun a => evalVector φ W a X) := by
  have : (fun a => evalVector φ W a X) =
      (WithLp.toLp 2) ∘ (fun a α => evalSingle φ W a (X α)) := rfl
  rw [this]
  refine (PiLp.continuous_toLp 2 _).comp (continuous_pi fun α => ?_)
  simp only [evalSingle]
  exact continuous_const.mul (continuous_finsetSum _ fun i _ =>
    (continuous_apply i).mul continuous_const)

lemma evalVector_measurable
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) :
    Measurable (fun a => evalVector φ W a X) :=
  (evalVector_continuous φ W X).measurable

lemma inner_evalVector_continuous
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (t : EuclideanSpace ℝ (Fin m)) :
    Continuous (fun a => ⟪t, evalVector φ W a X⟫) :=
  (innerSL ℝ t).continuous.comp (evalVector_continuous φ W X)

lemma inner_evalVector_measurable
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (t : EuclideanSpace ℝ (Fin m)) :
    Measurable (fun a => ⟪t, evalVector φ W a X⟫) :=
  (inner_evalVector_continuous φ W X t).measurable

/-! ### Initialization Probability Space and Independence Structure -/

/-- Transparent readout weight product measure on `Fin n → ℝ` with i.i.d. coordinates $\mathcal{N}(0, 1)$. -/
noncomputable abbrev gaussianReadoutMeasure (n : ℕ) : Measure (Fin n → ℝ) :=
  Measure.pi (fun _ : Fin n => gaussianReal 0 1)

/-- Instance: `gaussianInit n d` from `Basic.lean` is a probability measure. -/
instance instIsProbabilityMeasureGaussianInit (n d : ℕ) :
    IsProbabilityMeasure (gaussianInit n d) := by
  dsimp [gaussianInit]
  infer_instance

/-- Transparent joint initialization measure on `(Fin n → Fin d → ℝ) × (Fin n → ℝ)`
using the existing `NTK.gaussianInit` from `Basic.lean`. -/
noncomputable abbrev initMeasure (n d : ℕ) : Measure ((Fin n → Fin d → ℝ) × (Fin n → ℝ)) :=
  (gaussianInit n d).prod (gaussianReadoutMeasure n)

/-- Readout weight coordinates `a_i` have marginal standard normal distribution $\mathcal{N}(0, 1)$. -/
lemma map_gaussianReadoutMeasure_coord (i : Fin n) :
    Measure.map (fun a : Fin n → ℝ => a i) (gaussianReadoutMeasure n) = gaussianReal 0 1 :=
  (MeasureTheory.measurePreserving_eval (fun _ : Fin n => gaussianReal 0 1) i).map_eq

/-- Readout weights `a_i` are mutually independent across hidden units `i ∈ Fin n`. -/
lemma iIndepFun_readoutWeights (n : ℕ) :
    iIndepFun (fun i : Fin n => fun a : Fin n → ℝ => a i) (gaussianReadoutMeasure n) :=
  iIndepFun_pi (fun _ => aemeasurable_id)

/-- Input weight rows `W_i` have marginal standard Gaussian row distribution `𝒩(0, Iᵈ)`. -/
lemma map_gaussianInit_row (i : Fin n) :
    Measure.map (fun W : Fin n → Fin d → ℝ => W i) (gaussianInit n d) = gaussianRowMeasure d :=
  (MeasureTheory.measurePreserving_eval (fun _ : Fin n => gaussianRowMeasure d) i).map_eq

/-- Input weight rows `W_i` are mutually independent across hidden unit indices `i ∈ Fin n`. -/
lemma iIndepFun_inputWeights (n d : ℕ) :
    iIndepFun (fun i : Fin n => fun W : Fin n → Fin d → ℝ => W i) (gaussianInit n d) :=
  iIndepFun_pi (fun _ => aemeasurable_id)

/-- Mutual Independence: the family of input weights `W` is independent of readout weights `a`. -/
lemma indepFun_input_readout (n d : ℕ) :
    IndepFun (fun p : (Fin n → Fin d → ℝ) × (Fin n → ℝ) => p.1)
      (fun p : (Fin n → Fin d → ℝ) × (Fin n → ℝ) => p.2)
      (initMeasure n d) :=
  indepFun_prod measurable_id measurable_id

end Preliminaries

section Theorem1

/-! ## Theorem 1: Exact Finite-Width Conditional Normality -/

/-! ### Step 1 & Step 2: Linear Projections and ψ Coefficients -/

/-- The $\mathcal{F}$-measurable coefficients `ψ_i` for each hidden unit `i`:
  `ψ_i = (1/√n) ∑_α c_α φ(W i ⊙ X α)`. -/
noncomputable def psi
    (n : ℕ) (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (c : Fin m → ℝ) (i : Fin n) : ℝ :=
  (n : ℝ)⁻¹.sqrt * ∑ α : Fin m, c α * φ (W i ⊙ X α)

/-- **Step 1 (Linear projection identity)**:
For any linear combination vector `c : Fin m → ℝ`, the scalar linear projection of
the network output satisfies:
  `∑ α, c α * f(X α; W, a) = ∑ i, a i * ψ_i`. -/
lemma projection_eq_sum_psi
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (a : Fin n → ℝ)
    (X : Fin m → Fin d → ℝ) (c : Fin m → ℝ) :
    (∑ α : Fin m, c α * evalSingle φ W a (X α)) =
      ∑ i : Fin n, a i * psi n φ W X c i := by
  dsimp only [evalSingle, psi]
  simp_rw [Finset.mul_sum]
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro i _
  apply Finset.sum_congr rfl
  intro α _
  ring

/-! ### Step 4: Variance and Positive Semidefiniteness -/

/-- Auxiliary lemma: sum of products of coefficients and activations. -/
private lemma sum_psi_expand (n : ℕ) (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ)
    (X : Fin m → Fin d → ℝ) (c : Fin m → ℝ) (i : Fin n) :
    (psi n φ W X c i) ^ 2 =
      (n : ℝ)⁻¹ * ∑ α : Fin m, ∑ β : Fin m,
        c α * c β * (φ (W i ⊙ X α) * φ (W i ⊙ X β)) := by
  dsimp only [psi]
  have h_sqrt : ((n : ℝ)⁻¹.sqrt * ∑ α : Fin m, c α * φ (W i ⊙ X α)) ^ 2 =
      (n : ℝ)⁻¹ * (∑ α : Fin m, c α * φ (W i ⊙ X α)) ^ 2 := by
    rw [mul_pow, Real.sq_sqrt (by positivity)]
  rw [h_sqrt]
  congr 1
  rw [sq, Finset.sum_mul_sum]
  apply Finset.sum_congr rfl
  intro α _
  apply Finset.sum_congr rfl
  intro β _
  ring

/-- **Step 4 (Variance identity)**:
The sum of squared coefficients `∑ i, ψ_i^2` equals the quadratic form
`c ⬝ᵥ Φ^{(n)} *ᵥ c`:
  `∑ i, ψ_i^2 = c ⬝ᵥ Φ^{(n)} *ᵥ c`. -/
lemma sum_psi_sq_eq_bilin
    (n : ℕ) (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (c : Fin m → ℝ) :
    ∑ i : Fin n, (psi n φ W X c i) ^ 2 =
      c ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ c := by
  simp_rw [sum_psi_expand]
  simp only [dotProduct, mulVec, empiricalCovariance]
  simp_rw [Finset.mul_sum]
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro α _
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro β _
  have h_term : c α * ((∑ i : Fin n, (n : ℝ)⁻¹ * (φ (W i ⊙ X α) * φ (W i ⊙ X β))) * c β) =
      ∑ i : Fin n, (n : ℝ)⁻¹ * (c α * c β * (φ (W i ⊙ X α) * φ (W i ⊙ X β))) := by
    rw [Finset.sum_mul, Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro i _
    ring
  rw [h_term]

/-- The empirical covariance matrix `Φ^{(n)}` is symmetric (Hermitian). -/
lemma empiricalCovariance_isHermitian
    (n : ℕ) (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) :
    (empiricalCovariance n φ W X).IsHermitian := by
  ext α β
  simp only [empiricalCovariance, conjTranspose_apply, star_trivial]
  congr 1
  apply Finset.sum_congr rfl
  intro i _
  ring

/-- The quadratic form with `Φ^{(n)}` is always nonnegative. -/
lemma empiricalCovariance_nonneg
    (n : ℕ) (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (c : Fin m → ℝ) :
    0 ≤ c ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ c := by
  rw [← sum_psi_sq_eq_bilin]
  exact Finset.sum_nonneg (fun i _ => sq_nonneg (psi n φ W X c i))

/-- Finitely supported sum on a finite type coincides with universal sum when vanishing at zero. -/
private lemma finsupp_sum_eq_sum_univ {α β γ : Type*} [Fintype α] [Zero β] [AddCommMonoid γ]
    (x : α →₀ β) (f : α → β → γ) (hf : ∀ i, f i 0 = 0) :
    x.sum f = ∑ i : α, f i (x i) := by
  rw [Finsupp.sum, Finset.sum_subset (Finset.subset_univ x.support)]
  · intro i _ hi
    simp only [Finsupp.mem_support_iff, not_not] at hi
    rw [hi, hf]

/-- The empirical covariance matrix `Φ^{(n)}` is positive semidefinite (`PosSemidef`). -/
theorem empiricalCovariance_posSemidef
    (n : ℕ) (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) :
    (empiricalCovariance n φ W X).PosSemidef := by
  refine ⟨empiricalCovariance_isHermitian n φ W X, fun x => ?_⟩
  simp only [star_trivial]
  rw [finsupp_sum_eq_sum_univ _ _ (fun _ => by simp)]
  have h_inner (i : Fin m) :
      (x.sum fun j xj ↦ x i * empiricalCovariance n φ W X i j * xj) =
        ∑ j : Fin m, x i * empiricalCovariance n φ W X i j * x j := by
    rw [finsupp_sum_eq_sum_univ _ _ (fun _ => by simp)]
  simp_rw [h_inner]
  have h_dot : (∑ i : Fin m, ∑ j : Fin m, x i * empiricalCovariance n φ W X i j * x j) =
      (fun i => x i) ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ (fun i => x i) := by
    simp only [dotProduct, mulVec]
    apply Finset.sum_congr rfl
    intro i _
    rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro j _
    ring
  rw [h_dot]
  exact empiricalCovariance_nonneg n φ W X (fun i => x i)

/-! ### Step 3, 4 & 5: Conditional Distribution and Theorem 1 -/

/-- Pushforward of the readout measure under standard inner product with a vector `v : Fin n → ℝ`
is a 1D Gaussian with mean 0 and variance `∑ i, v i ^ 2`. -/
lemma map_gaussianReadoutMeasure_inner (v : Fin n → ℝ) :
    Measure.map (fun a : Fin n → ℝ => ∑ i : Fin n, a i * v i) (gaussianReadoutMeasure n) =
      gaussianReal 0 (Real.toNNReal (∑ i : Fin n, v i ^ 2)) := by
  have h_eq : (fun a : Fin n → ℝ => ∑ i : Fin n, a i * v i) =
      (fun (u : EuclideanSpace ℝ (Fin n)) => innerSL ℝ (WithLp.toLp 2 v) u) ∘ (WithLp.toLp 2) := by
    ext a
    dsimp [innerSL_apply_apply]
    rw [EuclideanSpace.inner_toLp_toLp]
    simp [dotProduct, mul_comm]
  rw [h_eq, ← Measure.map_map]
  · have h_toLp : Measure.map (WithLp.toLp 2) (gaussianReadoutMeasure n) =
        stdGaussian (EuclideanSpace ℝ (Fin n)) := map_pi_eq_stdGaussian
    rw [h_toLp]
    have h_map := IsGaussian.map_eq_gaussianReal
      (μ := stdGaussian (EuclideanSpace ℝ (Fin n))) (innerSL ℝ (WithLp.toLp 2 v))
    rw [h_map]
    have h_mean : ∫ (u : EuclideanSpace ℝ (Fin n)),
        (innerSL ℝ (WithLp.toLp 2 v)) u ∂stdGaussian (EuclideanSpace ℝ (Fin n)) = 0 := by
      rw [(innerSL ℝ (WithLp.toLp 2 v)).integral_comp_id_comm IsGaussian.integrable_id]
      rw [integral_id_stdGaussian]
      exact map_zero (innerSL ℝ (WithLp.toLp 2 v))
    have h_var : Var[innerSL ℝ (WithLp.toLp 2 v); stdGaussian (EuclideanSpace ℝ (Fin n))] =
        ∑ i : Fin n, v i ^ 2 := by
      rw [variance_dual_stdGaussian]
      rw [innerSL_apply_norm]
      simp only [EuclideanSpace.real_norm_sq_eq]
    rw [h_mean, h_var]
  all_goals fun_prop

/-- **Step 4 (Exact 1D Conditional Normality)**:
Conditional on `W`, every scalar linear projection `∑ α, c α * f(X α; W, a)` is distributed
as a univariate centered Gaussian with variance `c ⬝ᵥ Φ^{(n)} *ᵥ c`. -/
theorem map_readout_projection_eq_gaussianReal
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) (c : Fin m → ℝ) :
    Measure.map (fun a => ∑ α : Fin m, c α * evalSingle φ W a (X α)) (gaussianReadoutMeasure n) =
      gaussianReal 0 (Real.toNNReal (c ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ c)) := by
  have h_proj : (fun a => ∑ α : Fin m, c α * evalSingle φ W a (X α)) =
      (fun a => ∑ i : Fin n, a i * psi n φ W X c i) := by
    ext a
    exact projection_eq_sum_psi φ W a X c
  rw [h_proj]
  rw [map_gaussianReadoutMeasure_inner (psi n φ W X c)]
  congr 1
  rw [sum_psi_sq_eq_bilin]

/-- Pushforward under inner product with `t` yields a 1D Gaussian with variance
`t.ofLp ⬝ᵥ Φ^{(n)} *ᵥ t.ofLp`. -/
lemma map_readout_inner_evalVector
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (t : EuclideanSpace ℝ (Fin m)) :
    Measure.map (fun a => ⟪t, evalVector φ W a X⟫) (gaussianReadoutMeasure n) =
      gaussianReal 0 (Real.toNNReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ t.ofLp)) := by
  have h_eq : (fun a => ⟪t, evalVector φ W a X⟫) =
      (fun a => ∑ α : Fin m, t.ofLp α * evalSingle φ W a (X α)) := by
    ext a
    exact evalVector_inner φ W X a t
  rw [h_eq]
  exact map_readout_projection_eq_gaussianReal φ W X t.ofLp

/-- The characteristic function of `evalVector` under `gaussianReadoutMeasure n`. -/
lemma charFun_readout_evalVector
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ)
    (t : EuclideanSpace ℝ (Fin m)) :
    charFun (Measure.map (fun a => evalVector φ W a X) (gaussianReadoutMeasure n)) t =
      Complex.exp (- Complex.ofReal (t.ofLp ⬝ᵥ (empiricalCovariance n φ W X) *ᵥ t.ofLp) / 2) := by
  set μ := Measure.map (fun a => evalVector φ W a X) (gaussianReadoutMeasure n)
  rw [charFun_apply]
  have h_meas : Measurable (fun a => evalVector φ W a X) := evalVector_measurable φ W X
  rw [integral_map h_meas.aemeasurable (by fun_prop)]
  have h_exp : (fun a => Complex.exp (⟪evalVector φ W a X, t⟫ * Complex.I)) =
      (fun a => Complex.exp (⟪t, evalVector φ W a X⟫ * Complex.I)) := by
    ext a
    congr 1
    rw [real_inner_comm]
  rw [h_exp]
  have h_meas_inner : Measurable (fun a => ⟪t, evalVector φ W a X⟫) :=
    inner_evalVector_measurable φ W X t
  have h_int_map : (∫ a, Complex.exp (⟪t, evalVector φ W a X⟫ * Complex.I) ∂gaussianReadoutMeasure n) =
      ∫ y : ℝ, Complex.exp (y * Complex.I) ∂Measure.map (fun a => ⟪t, evalVector φ W a X⟫) (gaussianReadoutMeasure n) := by
    rw [integral_map h_meas_inner.aemeasurable (by fun_prop)]
  rw [h_int_map]
  rw [map_readout_inner_evalVector φ W X t]
  have h_cf_1 : (∫ y : ℝ, Complex.exp (y * Complex.I) ∂(gaussianReal 0 (Real.toNNReal (t.ofLp ⬝ᵥ empiricalCovariance n φ W X *ᵥ t.ofLp)))) =
      charFun (gaussianReal 0 (Real.toNNReal (t.ofLp ⬝ᵥ empiricalCovariance n φ W X *ᵥ t.ofLp))) 1 := by
    rw [charFun_apply_real]
    simp
  rw [h_cf_1, charFun_gaussianReal]
  simp only [Complex.ofReal_zero, mul_zero, zero_mul, Complex.ofReal_one, mul_one, one_pow, zero_sub]
  have h_nonneg : 0 ≤ t.ofLp ⬝ᵥ empiricalCovariance n φ W X *ᵥ t.ofLp :=
    empiricalCovariance_nonneg n φ W X t.ofLp
  rw [Real.coe_toNNReal _ h_nonneg]
  congr 1
  rw [neg_div]

/-- **Step 5 / Theorem 1 (Exact Conditional Normality)**:
Conditional on the input weights `W` (the sub-$\sigma$-algebra $\mathcal{F}$), the output
vector `f_m(W, a)` under the readout distribution is an exact centered multivariate Gaussian:
  `f_m | ℱ ~ 𝒩(0, Φ^{(n)})`.

Informal proof:
By the Cramér-Wold device (extensionality of characteristic functions in Mathlib),
two finite measures are equal if their Fourier transforms (characteristic functions) coincide.
For every projection vector `t ∈ EuclideanSpace ℝ (Fin m)`, the characteristic function of the
pushforward measure is computed via the 1D projection theorem to be
`exp(- (1/2) t ⬝ᵥ Φ^{(n)} *ᵥ t)`. This matches the characteristic function of Mathlib's
`multivariateGaussian 0 Φ^{(n)}` exactly, proving Theorem 1. -/
theorem exact_conditional_normality
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) :
    Measure.map (fun a => evalVector φ W a X) (gaussianReadoutMeasure n) =
      multivariateGaussian (0 : EuclideanSpace ℝ (Fin m)) (empiricalCovariance n φ W X) := by
  have hPos : (empiricalCovariance n φ W X).PosSemidef :=
    empiricalCovariance_posSemidef n φ W X
  apply Measure.ext_of_charFun
  ext t
  rw [charFun_readout_evalVector]
  rw [charFun_multivariateGaussian hPos]
  congr 1
  simp only [inner_zero_right, Complex.ofReal_zero, zero_mul, zero_sub, neg_div]

/-- The conditional distribution of the output vector satisfies `IsGaussian`. -/
instance isGaussian_conditional_output
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) :
    IsGaussian (Measure.map (fun a => evalVector φ W a X) (gaussianReadoutMeasure n)) := by
  rw [exact_conditional_normality]
  infer_instance

/-- The conditional expectation of the output vector vanishes. -/
lemma integral_conditional_output_eq_zero
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) :
    ∫ v, v ∂(Measure.map (fun a => evalVector φ W a X) (gaussianReadoutMeasure n)) = 0 := by
  rw [exact_conditional_normality]
  exact integral_id_multivariateGaussian

/-- The conditional covariance between outputs `f(X α)` and `f(X β)` is `Φ^{(n), α β}`. -/
lemma cov_conditional_output_eq_covariance
    (φ : ℝ → ℝ) (W : Fin n → Fin d → ℝ) (X : Fin m → Fin d → ℝ) (α β : Fin m) :
    cov[fun v => v.ofLp α, fun v => v.ofLp β;
      Measure.map (fun a => evalVector φ W a X) (gaussianReadoutMeasure n)] =
      empiricalCovariance n φ W X α β := by
  rw [exact_conditional_normality]
  have hPos : (empiricalCovariance n φ W X).PosSemidef :=
    empiricalCovariance_posSemidef n φ W X
  have (i : Fin m) : (fun (v : EuclideanSpace ℝ (Fin m)) => v.ofLp i) = (fun v => v i) := rfl
  rw [this, this]
  exact covariance_eval_multivariateGaussian hPos α β

end Theorem1

section Theorem2

/-! ## Theorem 2: Asymptotic Kernel Convergence and the NNGP Limit -/

/-! ### Step 1: Summand Measurability -/

/-- Step 1 (Measurability): For measurable `φ`, the product `w ↦ φ(w ⊙ x) * φ(w ⊙ x')` is measurable. -/
lemma measurable_cov_summand (φ : ℝ → ℝ) (hφ : Measurable φ) (x x' : Fin d → ℝ) :
    Measurable (fun w : Fin d → ℝ => φ (w ⊙ x) * φ (w ⊙ x')) :=
  (hφ.comp (measurable_innerProduct_left x)).mul (hφ.comp (measurable_innerProduct_left x'))

/-! ### Step 3: Integrability via Cauchy-Schwarz -/

/-- Step 3 (Integrability via Cauchy-Schwarz): If `φ(· ⊙ x)` and `φ(· ⊙ x')` are square-integrable
under the Gaussian row measure, their product is integrable. -/
lemma integrable_cov_summand_of_memLp
    (φ : ℝ → ℝ) (x x' : Fin d → ℝ)
    (hx : MemLp (fun w => φ (w ⊙ x)) 2 (gaussianRowMeasure d))
    (hx' : MemLp (fun w => φ (w ⊙ x')) 2 (gaussianRowMeasure d)) :
    Integrable (fun w => φ (w ⊙ x) * φ (w ⊙ x')) (gaussianRowMeasure d) :=
  hx.integrable_mul hx'

/-! ### Step 2 & Step 4: SLLN Convergence (Entrywise and Full Matrix) -/

/-- **Theorem 2 (Entrywise SLLN for the Covariance Tensor)**:
As width `n → ∞`, each entry of the empirical covariance matrix converges almost surely to the
deterministic limiting NNGP expectation:
  `Φ^{(n), α β} →_as 𝔼_{w ~ 𝒩(0, I_d)}[φ(w ⊙ X α) φ(w ⊙ X β)]`.

**Proof (4 Steps)**:
* Step 1: For fixed inputs `X α, X β`, define the summands `Y_i(rows) := φ(rows i ⊙ X α) φ(rows i ⊙ X β)`.
* Step 2: Because `rows` are i.i.d. under the infinite product measure `μ`, `{Y_i}` is i.i.d.
* Step 3: By square-integrability of `φ` and Cauchy-Schwarz (`MemLp.integrable_mul`), `Y_0` is integrable.
* Step 4: By Kolmogorov/Etemadi's SLLN (`strong_law_ae`), `(1/n) ∑_{i=1}^n Y_i →_as 𝔼[Y_0]`. -/
theorem empiricalCovariance_tendsto_integral
    (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ)
    (hφ_meas : Measurable φ)
    (hφ_L2 : ∀ α, MemLp (fun w => φ (w ⊙ X α)) 2 (gaussianRowMeasure d))
    (α β : Fin m) :
    ∀ᵐ rows : ℕ → Fin d → ℝ ∂(Measure.infinitePi fun _ => gaussianRowMeasure d),
      Filter.Tendsto
        (fun n : ℕ => empiricalCovariance n φ (fun i => rows i.val) X α β)
      Filter.atTop
      (nhds (∫ w, φ (w ⊙ X α) * φ (w ⊙ X β) ∂(gaussianRowMeasure d))) := by
  set g := fun w : Fin d → ℝ => φ (w ⊙ X α) * φ (w ⊙ X β)
  have hg_meas : Measurable g := measurable_cov_summand φ hφ_meas (X α) (X β)
  have hg_int : Integrable g (gaussianRowMeasure d) :=
    integrable_cov_summand_of_memLp φ (X α) (X β) (hφ_L2 α) (hφ_L2 β)
  simpa only [empiricalCovariance, g] using
    gaussianRow_average_tendsto_integral g hg_meas hg_int

/-- **Theorem 2 (Full Matrix Strong Law of Large Numbers for the Covariance Tensor)**:
As width `n → ∞`, the empirical covariance matrix converges almost surely to the deterministic
limiting NNGP Gram matrix in `Matrix (Fin m) (Fin m) ℝ`:
  `Φ^{(n)} →_as (fun α β => 𝔼_{w ~ 𝒩(0, I_d)}[φ(w ⊙ X α) φ(w ⊙ X β)])`. -/
theorem empiricalCovariance_tendsto_matrix_integral
    (φ : ℝ → ℝ) (X : Fin m → Fin d → ℝ)
    (hφ_meas : Measurable φ)
    (hφ_L2 : ∀ α, MemLp (fun w => φ (w ⊙ X α)) 2 (gaussianRowMeasure d)) :
    ∀ᵐ rows : ℕ → Fin d → ℝ ∂(Measure.infinitePi fun _ => gaussianRowMeasure d),
      Filter.Tendsto
        (fun n : ℕ => empiricalCovariance n φ (fun i => rows i.val) X)
        Filter.atTop
        (nhds ((fun α β => ∫ w, φ (w ⊙ X α) * φ (w ⊙ X β) ∂(gaussianRowMeasure d)) : Matrix (Fin m) (Fin m) ℝ)) := by
  have h_entry : ∀ α β : Fin m,
      ∀ᵐ rows : ℕ → Fin d → ℝ ∂(Measure.infinitePi fun _ => gaussianRowMeasure d),
        Filter.Tendsto
          (fun n : ℕ => empiricalCovariance n φ (fun i => rows i.val) X α β)
          Filter.atTop
          (nhds (∫ w, φ (w ⊙ X α) * φ (w ⊙ X β) ∂(gaussianRowMeasure d))) :=
    fun α β => empiricalCovariance_tendsto_integral φ X hφ_meas hφ_L2 α β
  have h_all :
      ∀ᵐ rows : ℕ → Fin d → ℝ ∂(Measure.infinitePi fun _ => gaussianRowMeasure d),
        ∀ α β : Fin m,
          Filter.Tendsto
            (fun n : ℕ => empiricalCovariance n φ (fun i => rows i.val) X α β)
            Filter.atTop
            (nhds (∫ w, φ (w ⊙ X α) * φ (w ⊙ X β) ∂(gaussianRowMeasure d))) := by
    simp_rw [ae_all_iff]
    exact h_entry
  filter_upwards [h_all] with rows hrows
  refine tendsto_pi_nhds.2 fun α => tendsto_pi_nhds.2 fun β => ?_
  exact hrows α β

end Theorem2

end NTK

end
