/-
Copyright (c) 2025 LML Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: LML Contributors
-/
module

public import LeanMachineLearning.Optimization.ConvexOpt.Basic
public import Mathlib.Probability.Martingale.Basic
public import Mathlib.Probability.Martingale.Convergence

/-!
# Stochastic gradient descent: high-probability convergence (§7.9)

This file formalizes the SGD analysis from §7.9 of the deep learning theory notes
(Telgarsky 2021).  The main results are:

1. **Approximate GD convergence** (Lemma 7.2): if the approximate gradient `gᵢ` differs from
   `∇f(wᵢ)` by noise `εᵢ`, the iterate average satisfies a convergence bound with error term
   `Σ εᵢ / t`.

2. **Azuma–Hoeffding inequality** (Theorem 7.8): for a bounded martingale difference sequence,
   the sum concentrates at rate `R√(2t ln(1/δ))`.

3. **SGD high-probability bound** (Lemma 7.3): combining the above, with high probability the
   SGD iterate average converges at rate `O(GD / √t)` to any reference `f(z)`.

## Measure-theoretic setup

We follow the pattern of `SequentialLearning` (using Mathlib's conditional expectation) but work
in a simpler setting where the filtration is generated by the iterates.  Full integration with
the `IsAlgEnvSeq` framework (for the bandit chapter) is noted as a future refactor.

## Main results

| Name | Statement |
|------|-----------|
| `ConvexOpt.approxGD_potential_step` | Potential bound for one approximate GD step |
| `ConvexOpt.approxGD_convergence` | Lemma 7.2: avg. convergence with noise term |
| `ConvexOpt.noise_is_martingale_diff` | The noise `εᵢ` is a martingale difference sequence |
| `ConvexOpt.azuma_hoeffding` | Theorem 7.8: Azuma–Hoeffding inequality |
| `ConvexOpt.sgd_convergence_expectation` | In-expectation bound |
| `ConvexOpt.sgd_high_prob_convergence` | Lemma 7.3: high-probability bound |

-/

@[expose] public section

open Real MeasureTheory ProbabilityTheory Filter Set Finset

namespace ConvexOpt

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

/-! ### Approximate GD convergence (Lemma 7.2) -/

/-- **Lemma 7.2** (Telgarsky 2021, Lemma 7.2).

For a convex function `f` and approximate gradient iterates `w_{i+1} = w_i - η · g_i`,
the potential `‖wᵢ - z‖²` satisfies a one-step bound:
  `2η(f(wᵢ) - f(z)) ≤ ‖wᵢ - z‖² - ‖w_{i+1} - z‖² + 2η · εᵢ + η² · ‖gᵢ‖²`
where `εᵢ = ⟪gᵢ - ∇f(wᵢ), z - wᵢ⟫` is the noise inner product. -/

theorem approxGD_convergence {f : E → ℝ} (hcvx : IsConvex f)
    {G : ℝ} (hG : 0 ≤ G) (c : ℝ) (hc : 0 < c)
    (g : ℕ → E) (hgbound : ∀ i, ‖g i‖ ≤ G)
    (w₀ z : E) {t : ℕ} (ht : 0 < t) :
    let w := approxGDIterate (c / Real.sqrt t) w₀ g
    (1 : ℝ) / t * ∑ i ∈ range t, f (w i) ≤
    f z
    + ‖w₀ - z‖ ^ 2 / (2 * c * Real.sqrt t)
    + c * G ^ 2 / (2 * Real.sqrt t)
    + 1 / t * ∑ i ∈ range t, approxNoiseTerm f g w z i := by
  sorry

/-! ### Martingale difference structure of noise -/

/-- Under a stochastic gradient oracle, the noise terms `εᵢ` form a martingale difference
sequence: `E[εᵢ | ℱᵢ] = 0`.

This is the key property used to apply Azuma–Hoeffding. -/
lemma noise_is_martingale_diff {Ω : Type*} [MeasurableSpace Ω] [MeasurableSpace E]
    {f : E → ℝ} (hf : Differentiable ℝ f)
    {P : Measure Ω} {w g : ℕ → Ω → E}
    {ℱ : ℕ → MeasurableSpace Ω}
    (hsgd : IsStochasticGradient f P w g ℱ)
    (z : Ω → E) (i : ℕ) :
    ∀ᵐ ω ∂P,
    condExp (ℱ i) P (fun ω => inner ℝ (g i ω - gradient f (w i ω)) (z ω - w i ω)) ω = 0 := by
  sorry

/-! ### Azuma–Hoeffding inequality (Theorem 7.8) -/

/-- A sequence `Z` is a martingale difference sequence w.r.t. filtration `ℱ` under `P`
if each `Z i` is integrable and adapted to `ℱ i`. -/
def MartingaleDiff {Ω : Type*} {mΩ : MeasurableSpace Ω} (Z : ℕ → Ω → ℝ) (ℱ : Filtration ℕ mΩ)
    (P : Measure Ω) : Prop :=
  ∀ i, Integrable (Z i) P

/-- **Theorem 7.8** (Azuma–Hoeffding, Telgarsky 2021, Theorem 7.8).

For a martingale difference sequence `(Zᵢ)` with `|Zᵢ| ≤ R` a.s.,
with probability at least `1 - δ`:
  `Σᵢ Zᵢ ≤ R · √(2t · ln(1/δ))`.

In Mathlib this follows from the Azuma inequality
(`MeasureTheory.Martingale.variance_le_sum_of_isBounded`
and the Hoeffding–Azuma bound).  We state it here as an independent theorem
to make the dependency explicit in the blueprint. -/
theorem azuma_hoeffding {Ω : Type*} [mΩ : MeasurableSpace Ω]
    {P : Measure Ω} [IsProbabilityMeasure P]
    {Z : ℕ → Ω → ℝ}
    {ℱ : Filtration ℕ mΩ}
    {R : ℝ} (hR : 0 ≤ R)
    (hmds : MartingaleDiff Z ℱ P)
    (hbound : ∀ i, ∀ᵐ ω ∂P, |Z i ω| ≤ R)
    {t : ℕ} {δ : ℝ} (hδ : 0 < δ) (hδ1 : δ < 1) :
    P.real {ω | ∑ i ∈ range t, Z i ω ≤ R * Real.sqrt (2 * (t : ℝ) * Real.log (1 / δ))} ≥ 1 - δ := by
  sorry

/-! ### In-expectation SGD bound -/

/-- Under a stochastic gradient oracle, the expected average iterate satisfies:
  `E[1/t Σ f(wᵢ)] ≤ f(z) + ‖w₀ - z‖² / (2√t) + G² / (2√t)`.

This is the simpler version that does not require Azuma–Hoeffding,
obtained by taking expectations and using `E[εᵢ] = 0`. -/
theorem sgd_convergence_expectation {Ω : Type*} [MeasurableSpace Ω] [MeasurableSpace E] [Nonempty Ω]
    {f : E → ℝ} (hcvx : IsConvex f) (hf : Differentiable ℝ f)
    {G : ℝ} (hG : 0 ≤ G) (c : ℝ) (hc : 0 < c)
    {P : Measure Ω} [IsProbabilityMeasure P]
    {w g : ℕ → Ω → E}
    {ℱ : ℕ → MeasurableSpace Ω}
    (hsgd : IsStochasticGradient f P w g ℱ)
    (hgbound : ∀ i, ∀ᵐ ω ∂P, ‖g i ω‖ ≤ G)
    (z : E) {t : ℕ} (ht : 0 < t) :
    P[fun ω => 1 / t * ∑ i ∈ range t, f (w i ω)] ≤
    f z + ‖w 0 (Classical.choice (by infer_instance : Nonempty Ω)) - z‖ ^ 2 / (2 * Real.sqrt t)
      + G ^ 2 / (2 * Real.sqrt t) := by
  sorry

/-! ### High-probability SGD bound (Lemma 7.3) -/

/-- **Lemma 7.3** (Telgarsky 2021, Lemma 7.3).

For a convex `f` with stochastic gradient oracle, step size `η = 1/√t`,
bounded gradients `‖gᵢ‖ ≤ G`, and bounded iterates `‖wᵢ - z‖ ≤ D`,
with probability at least `1 - δ`:
  `f(1/t Σ wᵢ) ≤ f(z) + D²/(2√t) + G²/(2√t) + 2DG√(2 ln(1/δ))/√t`.

The `2DG√(2 ln(1/δ))` term comes from applying Azuma–Hoeffding to `Σ εᵢ`. -/
theorem sgd_high_prob_convergence {Ω : Type*} [mΩ : MeasurableSpace Ω] [MeasurableSpace E] [Nonempty Ω]
    {f : E → ℝ} (hcvx : IsConvex f) (hf : Differentiable ℝ f)
    {G D : ℝ} (hG : 0 < G) (hD : 0 < D)
    {P : Measure Ω} [IsProbabilityMeasure P]
    {w g : ℕ → Ω → E}
    {ℱ : Filtration ℕ mΩ}
    (hsgd : IsStochasticGradient f P w g (ℱ : ℕ → MeasurableSpace Ω))
    (hgbound : ∀ i, ∀ᵐ ω ∂P, ‖g i ω‖ ≤ G)
    (z : E)
    (hdbound : ∀ i, ∀ᵐ ω ∂P, ‖w i ω - z‖ ≤ D)
    {t : ℕ} (ht : 0 < t) {δ : ℝ} (hδ : 0 < δ) (hδ1 : δ < 1) :
    P.real {ω |
      f (((1 : ℝ) / (t : ℝ)) • ∑ i ∈ range t, w i ω) ≤
      f z
      + D ^ 2 / (2 * Real.sqrt t)
      + G ^ 2 / (2 * Real.sqrt t)
      + 2 * D * G * Real.sqrt (2 * Real.log (1 / δ)) / Real.sqrt t} ≥ 1 - δ := by
  sorry

end ConvexOpt

end
